import Link from "next/link";
import { ArrowRight, CalendarClock, MessageSquareText, TrendingUp } from "lucide-react";
import FamilyShell, { Card, SectionTitle } from "./FamilyShell";
import { loadFamilyData, requireFamilyContext } from "@/lib/family";

const statusLabel: Record<string,string> = { attending: "参加", absent: "欠席", undecided: "未定", unanswered: "未回答" };
const fmt = (value: number | null) => value == null ? "—" : String(Math.round(value));

export default async function FamilyHome({ searchParams }: { searchParams: Promise<{ athlete?: string }> }) {
  const { athlete } = await searchParams;
  const context = await requireFamilyContext(athlete);
  const data = await loadFamilyData(context);
  return <FamilyShell context={context} active="/family">
    <div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm text-black/45">{context.guardianName}さん</p><h2 className="mt-1 text-3xl font-black tracking-[-.045em]">{context.athlete.name}さんの今</h2></div><span className="rounded-full bg-orange-100 px-3 py-1.5 text-xs font-black text-orange-700">{context.athlete.programClass ?? "会員"}</span></div>
    <div className="mt-7 grid gap-5 lg:grid-cols-2">
      <Card><SectionTitle eyebrow="THIS MONTH">今月の活動</SectionTitle><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{[["SESSION",data.activity.sessions],["CLASS",data.activity.classes],["CONTROL TEST",data.activity.controlTests],["PB更新",data.activity.pbUpdates]].map(([label,value])=><div key={label} className="rounded-xl bg-[#f5f2ec] p-4"><strong className="text-3xl">{value}</strong><p className="mt-1 text-[10px] font-black tracking-[.08em] text-black/45">{label}</p></div>)}</div></Card>
      <Card><div className="flex items-start justify-between"><SectionTitle eyebrow="RECENT GROWTH">最近の成長</SectionTitle><TrendingUp className="text-orange-500"/></div><div className="mt-5 space-y-3">{data.growth.map((item)=><div key={item.axis} className="grid grid-cols-[1fr_auto] items-center gap-4 border-b border-black/8 pb-3"><strong>{item.axis}</strong><span className="font-black">{fmt(item.previous)} → {fmt(item.current)} <em className={`ml-2 not-italic ${(item.delta ?? 0) >= 0 ? "text-emerald-600" : "text-black/40"}`}>{item.delta == null ? "" : `${item.delta >= 0 ? "+" : ""}${item.delta}`}</em></span></div>)}</div>{data.biggestGrowth ? <p className="mt-5 rounded-xl bg-orange-50 p-3 text-sm"><span className="font-black text-orange-700">BIGGEST GROWTH</span>　{data.biggestGrowth.axis} {data.biggestGrowth.delta! >= 0 ? "+" : ""}{data.biggestGrowth.delta}</p> : <p className="mt-5 text-sm text-black/45">次のCONTROL TESTで変化を確認できます。</p>}<Link href={`/family/growth?athlete=${context.athlete.id}`} className="mt-5 inline-flex items-center gap-2 text-sm font-black text-orange-600">詳しく見る <ArrowRight size={16}/></Link></Card>
      <Card><div className="flex items-start justify-between"><SectionTitle eyebrow="NEXT SESSION">次回予定</SectionTitle><CalendarClock className="text-orange-500"/></div>{data.nextSession ? <div className="mt-5"><p className="text-sm font-black text-orange-600">{new Date(data.nextSession.starts_at).toLocaleString("ja-JP",{month:"long",day:"numeric",weekday:"short",hour:"2-digit",minute:"2-digit"})}</p><h3 className="mt-2 text-xl font-black">{data.nextSession.title}</h3><p className="mt-2 text-sm text-black/50">{data.nextSession.location ?? "場所は後日案内"}</p><span className="mt-4 inline-flex rounded-full bg-black px-3 py-1.5 text-xs font-black text-white">出欠：{statusLabel[data.nextSession.attendance]}</span></div> : <p className="mt-5 text-sm text-black/45">現在、次回予定はありません。</p>}<Link href={`/family/schedule?athlete=${context.athlete.id}`} className="mt-5 inline-flex items-center gap-2 text-sm font-black text-orange-600">予定を見る <ArrowRight size={16}/></Link></Card>
      <Card><div className="flex items-start justify-between"><SectionTitle eyebrow="COACH MESSAGE">コーチから</SectionTitle><MessageSquareText className="text-orange-500"/></div>{data.report?.coach_message ? <blockquote className="mt-5 text-base font-medium leading-8 text-black/70">「{data.report.coach_message}」</blockquote> : <p className="mt-5 text-sm leading-7 text-black/45">今月のコメントは準備中です。記録だけでなく、取り組み方の変化もコーチからお伝えします。</p>}{data.announcements[0] ? <Link href={`/family/news?athlete=${context.athlete.id}`} className="mt-6 block rounded-xl border border-orange-200 bg-orange-50 p-4"><p className="text-[10px] font-black text-orange-700">IMPORTANT NEWS</p><strong className="mt-1 block">{data.announcements[0].title}</strong></Link> : null}</Card>
    </div>
  </FamilyShell>;
}
