import Link from "next/link";
import { ArrowLeft, CalendarClock, MapPin } from "lucide-react";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase-server";
import { bookPersonalSession, cancelPersonalSession } from "./actions";

function dateTime(value: string) { return new Date(value).toLocaleString("ja-JP", { month: "numeric", day: "numeric", weekday: "short", hour: "2-digit", minute: "2-digit", timeZone: "Asia/Tokyo" }); }
function time(value: string) { return new Date(value).toLocaleTimeString("ja-JP", { hour: "2-digit", minute: "2-digit", timeZone: "Asia/Tokyo" }); }

export default async function PersonalSessionsPage({ searchParams }: { searchParams: Promise<{ booked?: string; cancelled?: string; error?: string }> }) {
  const query = await searchParams; const supabase = await createClient(); const { data: authData } = await supabase.auth.getClaims(); const userId = authData?.claims.sub;
  if (!userId) redirect("/login?next=/mypage/personal");
  const [{ data: slots }, { data: bookings }] = await Promise.all([
    supabase.from("schedules").select("id,title,details,location,starts_at,ends_at,personal_booked").eq("is_personal_slot", true).gte("starts_at", new Date().toISOString()).order("starts_at").limit(60),
    supabase.from("personal_session_bookings").select("schedule_id,note").eq("user_id", userId),
  ]);
  const mine = new Map((bookings ?? []).map((item) => [item.schedule_id, item.note]));
  return <main className="min-h-screen bg-[#090a0c] px-5 pb-20 pt-28 text-white"><div className="mx-auto max-w-3xl"><Link href="/mypage" className="inline-flex items-center gap-2 text-xs font-bold text-white/55"><ArrowLeft size={16}/>MY PAGE</Link><header className="mt-8 border-l-2 border-orange-500 pl-5"><p className="text-[10px] font-black tracking-[.2em] text-orange-400">PERSONAL SESSION</p><h1 className="mt-2 text-3xl font-black">パーソナル予約</h1><p className="mt-2 text-sm text-white/45">空いている時間を選び、取り組みたい内容を送ってください。</p></header>{query.booked ? <p className="mt-6 rounded-xl bg-emerald-400/10 p-4 text-sm font-bold text-emerald-300">予約しました。マイカレンダーにも参加予定として反映されます。</p> : null}{query.cancelled ? <p className="mt-6 rounded-xl bg-white/[.06] p-4 text-sm text-white/60">予約をキャンセルしました。</p> : null}{query.error ? <p className="mt-6 rounded-xl bg-red-500/10 p-4 text-sm font-bold text-red-300">{query.error}</p> : null}<div className="mt-7 space-y-3">{(slots ?? []).map((slot) => { const isMine = mine.has(slot.id); const unavailable = slot.personal_booked && !isMine; return <article key={slot.id} className={`rounded-2xl border p-5 ${isMine ? "border-emerald-400/35 bg-emerald-400/[.07]" : unavailable ? "border-white/[.06] bg-white/[.02] opacity-55" : "border-orange-400/20 bg-[#111]"}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="flex items-center gap-2 text-sm font-black"><CalendarClock size={17} className="text-orange-400"/>{dateTime(slot.starts_at)}〜{slot.ends_at ? time(slot.ends_at) : ""}</p>{slot.location ? <p className="mt-2 flex items-center gap-1 text-xs text-white/40"><MapPin size={13}/>{slot.location}</p> : null}</div><span className={`rounded-full px-3 py-1 text-[10px] font-black ${isMine ? "bg-emerald-400 text-black" : unavailable ? "bg-white/10 text-white/45" : "bg-orange-500 text-black"}`}>{isMine ? "予約済み" : unavailable ? "受付終了" : "空き"}</span></div>{isMine ? <form action={cancelPersonalSession} className="mt-4"><input type="hidden" name="schedule_id" value={slot.id}/><button className="rounded-lg border border-red-400/30 px-4 py-2 text-xs font-black text-red-300">予約をキャンセル</button></form> : !unavailable ? <form action={bookPersonalSession} className="mt-4 flex flex-col gap-2 sm:flex-row"><input type="hidden" name="schedule_id" value={slot.id}/><input name="note" maxLength={500} placeholder="相談・練習したい内容（任意）" className="min-w-0 flex-1 rounded-xl border border-white/10 bg-black/30 px-4 py-3 text-sm"/><button className="rounded-xl bg-orange-500 px-5 py-3 text-sm font-black text-black">この枠を予約</button></form> : null}</article>; })}{!slots?.length ? <p className="rounded-2xl border border-white/10 p-8 text-center text-sm text-white/40">現在公開中のパーソナル枠はありません。</p> : null}</div></div></main>;
}
