"use client";
import { FormEvent, useState } from "react";
import { CheckCircle2, Send } from "lucide-react";
import { createClient } from "@/lib/supabase-browser";

export type DirectMessage={id:number;sender_id:string;sender_role:"athlete"|"coach";body:string;created_at:string};
export default function AiCoachDirectChat({consultationId,userId,role,initialMessages,initialStatus}:{consultationId:string;userId:string;role:"athlete"|"coach";initialMessages:DirectMessage[];initialStatus:string}){
 const [messages,setMessages]=useState(initialMessages),[body,setBody]=useState(""),[status,setStatus]=useState(initialStatus),[saving,setSaving]=useState(false),[error,setError]=useState("");
 async function send(e:FormEvent){e.preventDefault();const value=body.trim();if(!value)return;setSaving(true);setError("");const supabase=createClient();const {data,error:insertError}=await supabase.from("ai_coach_consultation_messages").insert({consultation_id:consultationId,sender_id:userId,sender_role:role,body:value}).select("id,sender_id,sender_role,body,created_at").single();if(insertError)setError(insertError.message);else{setMessages(v=>[...v,data as DirectMessage]);setBody("");if(status==="pending"){await supabase.from("ai_coach_consultations").update({status:"active",assigned_coach_id:role==="coach"?userId:undefined,updated_at:new Date().toISOString()}).eq("id",consultationId);setStatus("active")}}setSaving(false)}
 async function resolve(){const supabase=createClient();const {error:updateError}=await supabase.from("ai_coach_consultations").update({status:"resolved",resolved_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",consultationId);if(updateError)setError(updateError.message);else setStatus("resolved")}
 return <section className="mt-6 rounded-2xl border border-white/10 bg-black/20 p-4 sm:p-5"><div className="flex items-center justify-between"><h2 className="font-black">選手・コーチ直接トーク</h2><span className={`rounded-full px-3 py-1 text-[10px] font-black ${status==="resolved"?"bg-emerald-500/15 text-emerald-300":"bg-sky-500/15 text-sky-300"}`}>{status==="resolved"?"解決済み":"相談中"}</span></div><p className="mt-2 text-xs text-white/40">ここから先はAIを介さず、選手と担当コーチが直接やり取りします。</p><div className="mt-5 space-y-3">{messages.length?messages.map(m=><div key={m.id} className={`flex ${m.sender_role===role?"justify-end":"justify-start"}`}><div className={`max-w-[88%] rounded-2xl px-4 py-3 ${m.sender_role==="coach"?"bg-sky-950 text-sky-50":"bg-orange-950 text-orange-50"}`}><p className="text-[10px] font-black opacity-55">{m.sender_role==="coach"?"コーチ":"選手"}</p><p className="mt-1 whitespace-pre-wrap text-sm leading-6">{m.body}</p><p className="mt-2 text-[9px] opacity-35">{new Date(m.created_at).toLocaleString("ja-JP")}</p></div></div>):<p className="py-8 text-center text-xs text-white/30">コーチの確認を待っています</p>}</div>{status!=="resolved"?<form onSubmit={send} className="mt-5 border-t border-white/10 pt-4"><textarea value={body} onChange={e=>setBody(e.target.value)} maxLength={2000} rows={3} placeholder={role==="coach"?"選手へ返信する":"追加の質問や結果を入力"} className="w-full resize-none rounded-xl border border-white/15 bg-[#090a0c] px-4 py-3 text-sm text-white outline-none focus:border-sky-400"/><div className="mt-2 flex justify-between gap-2"><button type="button" onClick={()=>void resolve()} className="flex items-center gap-2 rounded-xl border border-emerald-500/25 px-4 py-3 text-xs font-black text-emerald-300"><CheckCircle2 size={15}/>解決済みにする</button><button disabled={saving||!body.trim()} className="flex items-center gap-2 rounded-xl bg-sky-400 px-5 py-3 text-xs font-black text-black disabled:opacity-40"><Send size={15}/>送信</button></div></form>:null}{error?<p className="mt-3 text-xs text-red-300">{error}</p>:null}</section>}
