"use client";
import Link from "next/link";
import { FormEvent, useCallback, useEffect, useRef, useState } from "react";
import { ArrowRight, Compass, History, LoaderCircle, MessageCircleMore, Plus, Send, UserRound, X } from "lucide-react";
import { initialCompanionAnswer, navigatorPrinciples, type CompanionAnswer } from "@/lib/ai-navigator/knowledge";

export type Conversation = { id:string; title:string; status:string; resolution_status?:string; coach_handoff_at?:string|null; last_message_at:string; created_at:string };
export type Message = { id:number|string; role:"user"|"companion"; content:string; response_payload:CompanionAnswer|Record<string,never>; created_at:string };
export type CompanionInitialData = { conversations:Conversation[]; activeId:string|null; messages:Message[] };
type Draft = { eventName:string; consultation:string; currentFeeling:string; triedActions:string; dataSummary:string; requestedFocus:string; attachmentCandidates:Array<{label:string;kind:string}> };

export default function AiNavigator({initialData}:{initialData:CompanionInitialData}) {
  const [conversations,setConversations]=useState(initialData.conversations), [activeId,setActiveId]=useState(initialData.activeId), [messages,setMessages]=useState(initialData.messages);
  const [input,setInput]=useState(""), [loading,setLoading]=useState(false), [sending,setSending]=useState(false), [historyOpen,setHistoryOpen]=useState(false), [error,setError]=useState("");
  const [draft,setDraft]=useState<Draft|null>(null), [consultationId,setConsultationId]=useState<string|null>(null); const endRef=useRef<HTMLDivElement>(null);
  const load=useCallback(async(id?:string|null)=>{setLoading(true);const r=await fetch(`/api/ai-companion${id?`?conversationId=${encodeURIComponent(id)}`:""}`,{cache:"no-store"}),d=await r.json();if(r.ok){setConversations(d.conversations);setActiveId(d.activeId);setMessages(d.messages);setConsultationId(d.consultationId??null)}else setError(d.error);setLoading(false)},[]);
  useEffect(()=>{endRef.current?.scrollIntoView({behavior:"smooth",block:"end"})},[messages]);
  async function send(text:string){const value=text.trim();if(!value||sending)return;setSending(true);setError("");setInput("");const optimistic:Message={id:`p-${Date.now()}`,role:"user",content:value,response_payload:{},created_at:new Date().toISOString()};setMessages(v=>[...v,optimistic]);const r=await fetch("/api/ai-companion",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({conversationId:activeId,message:value})}),d=await r.json();if(!r.ok){setMessages(v=>v.filter(x=>x.id!==optimistic.id));setError(d.error||"送信できませんでした。")}else{setActiveId(d.conversationId);setMessages(v=>[...v.filter(x=>x.id!==optimistic.id),...d.messages]);if(d.isNew)await load(d.conversationId)}setSending(false)}
  async function handoff(action:"preview"|"submit"){if(!activeId){setError("先に相談内容を一つ送ってください。");return}setSending(true);const r=await fetch("/api/ai-companion/handoff",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({conversationId:activeId,action,draft})}),d=await r.json();setSending(false);if(!r.ok)setError(d.error);else if(d.alreadySent||action==="submit"){setConsultationId(d.consultationId);setDraft(null);await load(activeId)}else setDraft(d.draft)}
  const visible=messages.length?messages:[{id:"initial",role:"companion" as const,content:"",response_payload:initialCompanionAnswer,created_at:""}];
  return <div className="space-y-5">
    <section className="rounded-3xl border border-orange-500/40 bg-[radial-gradient(circle_at_top_right,rgba(249,115,22,.16),transparent_38%),#111] p-5 sm:p-8"><div className="flex gap-4"><span className="grid h-14 w-14 shrink-0 place-items-center rounded-2xl bg-orange-500/10 text-orange-400"><Compass size={29}/></span><div><p className="text-[10px] font-black tracking-[.2em] text-orange-400">REFLECTION・NAVIGATION・CONNECTION</p><h1 className="mt-2 text-3xl font-black">話して、整理して、コーチへつなぐ。</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-white/55">答えを決めつけず、自分の状態を言葉にして次の行動を選ぶ相談パートナーです。必要な時は、整理した内容を担当コーチへ送れます。</p></div></div><div className="mt-6 flex flex-wrap gap-2">{navigatorPrinciples.map(x=><span key={x} className="rounded-full border border-white/10 px-3 py-2 text-[10px] text-white/45">{x}</span>)}</div></section>
    <div className="flex gap-2"><button onClick={()=>{setActiveId(null);setMessages([]);setConsultationId(null);setError("")}} className="flex flex-1 items-center justify-center gap-2 rounded-xl bg-orange-500 px-4 py-3 text-xs font-black text-black"><Plus size={16}/>新しい相談</button><button onClick={()=>setHistoryOpen(true)} className="flex items-center gap-2 rounded-xl border border-white/15 bg-[#111] px-4 py-3 text-xs font-black text-white/65"><History size={16}/>過去の相談 {conversations.length}</button></div>
    <section className="rounded-3xl border border-white/10 bg-[#111] p-4 sm:p-6">{loading?<div className="grid min-h-56 place-items-center"><LoaderCircle className="animate-spin text-white/30"/></div>:<div className="space-y-5">{visible.map(m=>m.role==="user"?<div key={m.id} className="flex justify-end"><div className="max-w-[88%] rounded-2xl rounded-tr-sm bg-orange-500 px-4 py-3 text-sm font-bold text-black">{m.content}</div></div>:<Bubble key={m.id} message={m as Message} onPrompt={send} onHandoff={()=>handoff("preview")}/>)}</div>}{sending?<p className="mt-5 flex items-center gap-2 text-xs text-white/35"><LoaderCircle size={15} className="animate-spin"/>内容を整理しています…</p>:null}<div ref={endRef}/>{error?<p className="mt-4 rounded-xl border border-red-500/25 p-3 text-xs text-red-200">{error}</p>:null}{consultationId?<Link href={`/mypage/ai-consultations/${consultationId}`} className="mt-5 flex items-center justify-between rounded-xl border border-sky-400/35 bg-sky-400/[.07] px-4 py-4 text-sm font-black text-sky-200">コーチとの直接トークを開く<ArrowRight size={16}/></Link>:null}<form onSubmit={(e:FormEvent)=>{e.preventDefault();void send(input)}} className="mt-6 border-t border-white/10 pt-5"><label htmlFor="ai-input" className="text-xs font-black text-white/45">VAULTEX AIに話す</label><div className="mt-2 flex gap-2"><textarea id="ai-input" rows={2} maxLength={1000} value={input} onChange={e=>setInput(e.target.value)} placeholder="例：最近、踏切の感覚が合わない" className="min-w-0 flex-1 resize-none rounded-xl border border-white/15 bg-[#090a0c] px-4 py-3 text-sm text-white outline-none focus:border-orange-500"/><button disabled={!input.trim()||sending} className="grid w-12 place-items-center rounded-xl bg-orange-500 text-black disabled:opacity-35"><Send size={18}/></button></div></form></section>
    <section className="grid gap-3 sm:grid-cols-2"><Info title="本人データだけを参照" body="本人の記録・意識・動画の有無・SCANだけを振り返りの材料にします。"/><Info title="人との関係へ接続" body="AIで整理した後は担当コーチとの直接トークへ移り、AIが間に入り続けることはありません。"/></section>
    {historyOpen?<div className="fixed inset-0 z-[100] bg-black/75 p-4" onClick={()=>setHistoryOpen(false)}><div className="ml-auto h-full max-w-md overflow-y-auto rounded-3xl border border-white/10 bg-[#111] p-5" onClick={e=>e.stopPropagation()}><div className="flex justify-between"><h2 className="text-xl font-black">過去の相談</h2><button onClick={()=>setHistoryOpen(false)}><X/></button></div><div className="mt-6 space-y-2">{conversations.map(c=><button key={c.id} onClick={()=>{setHistoryOpen(false);void load(c.id)}} className="flex w-full items-center gap-3 rounded-2xl border border-white/10 p-4 text-left"><MessageCircleMore className="text-orange-400"/><span className="min-w-0 flex-1"><strong className="block truncate text-sm">{c.title}</strong><small className="text-white/35">{c.coach_handoff_at?"コーチ相談へ送信済み":new Date(c.last_message_at).toLocaleString("ja-JP")}</small></span></button>)}</div></div></div>:null}
    {draft?<Modal draft={draft} setDraft={setDraft} loading={sending} submit={()=>handoff("submit")}/>:null}
  </div>}

function Bubble({message,onPrompt,onHandoff}:{message:Message;onPrompt:(s:string)=>Promise<void>;onHandoff:()=>Promise<void>}){const a=message.response_payload as CompanionAnswer;if(!a?.title)return null;return <div className="flex gap-3"><Compass size={20} className="mt-3 shrink-0 text-orange-400"/><div className="min-w-0 flex-1 rounded-2xl border border-white/10 bg-black/20 p-4"><p className="font-black">{a.title}</p><p className="mt-2 whitespace-pre-line text-sm leading-6 text-white/55">{a.body}</p>{a.question?<p className="mt-3 text-sm font-bold text-white/75">{a.question}</p>:null}<div className="mt-4 grid gap-2 sm:grid-cols-2">{a.actions.map(x=>x.handoff?<button key={x.label} onClick={()=>void onHandoff()} className="flex justify-between rounded-xl border border-sky-400/35 px-4 py-3 text-left text-xs font-black text-sky-200">{x.label}<UserRound size={14}/></button>:x.href?<Link key={x.label} href={x.href} className="flex justify-between rounded-xl border border-orange-500/30 px-4 py-3 text-xs font-black text-orange-200">{x.label}<ArrowRight size={14}/></Link>:<button key={x.label} onClick={()=>void onPrompt(x.prompt||x.label)} className="flex justify-between rounded-xl border border-white/10 px-4 py-3 text-left text-xs font-black text-white/65">{x.label}<ArrowRight size={14}/></button>)}</div></div></div>}
function Info({title,body}:{title:string;body:string}){return <div className="rounded-2xl border border-white/10 bg-[#111] p-4"><p className="text-xs font-black text-orange-300">{title}</p><p className="mt-2 text-xs leading-5 text-white/40">{body}</p></div>}
function Modal({draft,setDraft,loading,submit}:{draft:Draft;setDraft:(d:Draft|null)=>void;loading:boolean;submit:()=>Promise<void>}){const field=(k:"eventName"|"consultation"|"currentFeeling"|"triedActions"|"requestedFocus",label:string)=><label className="block"><span className="text-xs font-black text-white/55">{label}</span><textarea rows={k==="consultation"?3:2} value={draft[k]} onChange={e=>setDraft({...draft,[k]:e.target.value})} className="mt-2 w-full resize-none rounded-xl border border-white/15 bg-[#090a0c] px-4 py-3 text-sm text-white"/></label>;return <div className="fixed inset-0 z-[110] overflow-y-auto bg-black/80 p-4"><div className="mx-auto my-8 max-w-2xl rounded-3xl border border-sky-400/30 bg-[#111] p-5 sm:p-7"><div className="flex justify-between"><div><p className="text-xs font-black text-sky-300">COACH CONNECTION</p><h2 className="mt-2 text-2xl font-black">コーチへ送る内容を確認</h2><p className="mt-2 text-xs text-white/45">自由に修正できます。送信後は選手とコーチが直接やり取りします。</p></div><button onClick={()=>setDraft(null)}><X/></button></div><div className="mt-6 space-y-4">{field("eventName","種目")}{field("consultation","相談内容")}{field("currentFeeling","現在の感覚")}{field("triedActions","試したこと")}{field("requestedFocus","確認してほしい内容")}<div className="rounded-xl border border-white/10 p-4"><p className="text-xs font-black">過去データからの手がかり</p><p className="mt-2 text-xs leading-5 text-white/45">{draft.dataSummary}</p></div><p className="text-xs text-white/40">添付候補：{draft.attachmentCandidates.map(x=>x.label).join("・")||"なし"}</p></div><button disabled={loading||!draft.consultation.trim()} onClick={()=>void submit()} className="mt-6 flex w-full justify-center gap-2 rounded-xl bg-sky-400 px-5 py-4 text-sm font-black text-black disabled:opacity-40"><Send size={17}/>コーチへ相談を送る</button></div></div>}
