"use client";

import { Radar, RadarChart, PolarAngleAxis, PolarGrid, PolarRadiusAxis, ResponsiveContainer } from "recharts";
import { ArrowUpRight, CircleGauge, Sparkles } from "lucide-react";
import { abilityKeys, type AthleteScanEvaluation } from "@/lib/athlete-scan";

type Comparison = { previous: AthleteScanEvaluation | null; first: AthleteScanEvaluation | null };
const axisJa = { SPEED:"速度特性", POWER:"出力特性", REACTIVE:"反発特性" } as const;
const signed = (value: number) => `${value > 0 ? "+" : ""}${Math.round(value)}`;
const score = (value: number | null) => value == null ? "評価準備中" : String(Math.round(value));

export default function AthleteScanResult({ evaluation, comparison, scanNumber, measuredOn, standardLabel }:{ evaluation:AthleteScanEvaluation; comparison:Comparison; scanNumber:number; measuredOn:string; standardLabel:string }) {
  const chart = (Object.keys(evaluation.axes) as Array<keyof typeof evaluation.axes>).map((key)=>({axis:key,value:evaluation.axes[key] ?? 0}));
  const chartMax = Math.max(100, Math.ceil(Math.max(...chart.map((item)=>item.value),100)/20)*20);
  const previousType = comparison.previous?.typeNameJa;
  return <div className="space-y-7">
    <section className="overflow-hidden rounded-3xl border border-orange-500/40 bg-[radial-gradient(circle_at_top_right,rgba(249,115,22,.18),transparent_38%),#111] p-6 sm:p-9">
      <div className="flex flex-wrap items-start justify-between gap-5"><div><p className="text-[10px] font-black tracking-[.24em] text-orange-400">VAULTEX ATHLETE SCAN</p><h1 className="mt-2 text-3xl font-black sm:text-5xl">SCAN #{String(scanNumber).padStart(2,"0")}</h1><p className="mt-2 text-sm text-white/45">測定日 {measuredOn}</p></div><span className="rounded-full border border-orange-500/35 bg-orange-500/10 px-4 py-2 text-[10px] font-black tracking-[.14em] text-orange-300">VER.1 BETA</span></div>
      <div className="mt-8 border-t border-white/10 pt-7"><p className="text-xs font-black tracking-[.18em] text-white/45">YOUR ATHLETE TYPE</p>{evaluation.typeCode ? <><p className="mt-3 text-2xl font-black text-orange-400 sm:text-4xl">{evaluation.typeCode}</p><h2 className="mt-1 text-xl font-bold">{evaluation.typeNameJa}</h2><p className="mt-4 max-w-3xl text-sm leading-7 text-white/60">{evaluation.typeDescription}</p></> : <><h2 className="mt-3 text-2xl font-black">評価準備中</h2><p className="mt-3 text-sm leading-6 text-white/50">3つの身体特性を確定するための測定値、またはSTANDARDが不足しています。未測定は0点として扱いません。</p></>}</div>
      {evaluation.nextGrowth ? <div className="mt-6 rounded-2xl border border-cyan-400/20 bg-cyan-400/[.06] p-4"><p className="flex items-center gap-2 text-xs font-black tracking-[.15em] text-cyan-300"><Sparkles size={15}/>NEXT GROWTH</p><p className="mt-2 text-sm text-white/65">次に変化を追いたい領域：<b className="text-white">{axisJa[evaluation.nextGrowth]} / {evaluation.nextGrowth}</b></p></div> : null}
    </section>

    <section className="grid gap-5 rounded-3xl border border-white/10 bg-[#111] p-5 lg:grid-cols-[1fr_1.1fr] lg:p-7">
      <div><p className="text-[10px] font-black tracking-[.2em] text-orange-400">BODY CHARACTERISTICS</p><h2 className="mt-1 text-2xl font-black">3つの身体特性</h2><div className="mt-5 grid gap-3">{(Object.entries(evaluation.axes) as Array<[keyof typeof evaluation.axes,number|null]>).map(([key,value])=><div key={key} className="rounded-2xl bg-white/[.035] p-4"><div className="flex items-end justify-between gap-3"><div><p className="font-black">{key}</p><p className="text-xs text-white/40">{axisJa[key]}</p></div><strong className="text-3xl text-orange-400">{score(value)}</strong></div>{value!=null?<div className="mt-3 h-1.5 overflow-hidden rounded-full bg-white/10"><span className="block h-full rounded-full bg-orange-500" style={{width:`${Math.min(100,Math.max(0,value))}%`}}/></div>:null}</div>)}</div></div>
      <div className="h-[330px] min-w-0"><ResponsiveContainer width="100%" height="100%"><RadarChart data={chart} outerRadius="72%"><PolarGrid stroke="rgba(255,255,255,.15)"/><PolarAngleAxis dataKey="axis" tick={{fill:"rgba(255,255,255,.7)",fontSize:11,fontWeight:800}}/><PolarRadiusAxis domain={[0,chartMax]} tick={{fill:"rgba(255,255,255,.3)",fontSize:9}} axisLine={false}/><Radar dataKey="value" stroke="#f97316" fill="#f97316" fillOpacity={.32} strokeWidth={3}/></RadarChart></ResponsiveContainer></div>
    </section>

    <section><div className="flex items-end justify-between"><div><p className="text-[10px] font-black tracking-[.2em] text-orange-400">ABILITY DETAILS</p><h2 className="mt-1 text-2xl font-black">6つの能力</h2></div><CircleGauge className="text-orange-400"/></div><div className="mt-4 grid gap-4 lg:grid-cols-2">{abilityKeys.map((key)=>{const item=evaluation.abilities[key];const previous=comparison.previous?.abilities[key]?.score??null;const first=comparison.first?.abilities[key]?.score??null;return <article key={key} className="rounded-2xl border border-white/10 bg-[#111] p-5"><div className="flex justify-between gap-4"><div><h3 className="font-black">{item.nameJa}</h3><p className="mt-1 text-[9px] font-black tracking-[.12em] text-orange-400">{item.nameEn}</p></div><div className="text-right"><strong className="text-3xl">{score(item.score)}</strong>{item.score!=null?<span className="ml-1 text-[10px] text-white/35">SCORE</span>:null}{item.score!=null&&item.score>=100?<span className="mt-1 block text-[9px] font-black tracking-wider text-cyan-300">BEYOND STANDARD</span>:null}</div></div><dl className="mt-5 grid grid-cols-2 gap-2 text-xs"><Data label="実測値" value={item.rawValue==null?"—":`${item.rawValue}${item.unit}`}/><Data label="使用テスト" value={item.testName}/><Data label="100 STANDARD" value={item.standard?.score_100_value==null?"VAULTEX STANDARD設定中":String(item.standard.score_100_value)}/><Data label="前回SCAN差" value={item.score==null||previous==null?"—":signed(item.score-previous)}/><Data label="初回SCAN差" value={item.score==null||first==null?"—":signed(item.score-first)}/></dl></article>})}</div></section>

    {comparison.previous ? <section className="rounded-3xl border border-cyan-400/20 bg-cyan-400/[.035] p-5 sm:p-7"><p className="text-[10px] font-black tracking-[.2em] text-cyan-300">PROFILE EVOLUTION</p><h2 className="mt-1 text-2xl font-black">前回SCANからの変化</h2><div className="mt-5 grid gap-3 sm:grid-cols-3">{(Object.keys(evaluation.axes) as Array<keyof typeof evaluation.axes>).map((key)=>{const before=comparison.previous?.axes[key]??null;const after=evaluation.axes[key];return <div key={key} className="rounded-xl bg-black/20 p-4"><p className="text-xs font-black">{key}</p><p className="mt-2 text-xl font-black">{before==null||after==null?"評価準備中":<>{Math.round(before)} <ArrowUpRight className="inline text-cyan-300" size={16}/> {Math.round(after)} <span className="ml-2 text-sm text-cyan-300">{signed(after-before)}</span></>}</p></div>})}</div>{previousType&&evaluation.typeNameJa&&previousType!==evaluation.typeNameJa?<p className="mt-5 rounded-xl border border-white/10 p-4 text-sm text-white/60">前回 <b>{previousType}</b> → 今回 <b className="text-orange-300">{evaluation.typeNameJa}</b></p>:null}</section>:null}

    <section className="rounded-2xl border border-orange-500/25 bg-orange-500/[.045] p-5"><p className="font-black text-orange-300">{standardLabel}</p><p className="mt-3 text-xs leading-6 text-white/50">VAULTEX SCOREは、SHONAI VAULTEXが身体能力の成長を可視化するために設定した独自評価基準です。100はVAULTEX STANDARDへの到達を示し、満点ではありません。測定データや研究知見の蓄積に伴い、基準値・評価方法を更新する場合があります。</p></section>
  </div>;
}

function Data({label,value}:{label:string;value:string}) { return <div className="rounded-lg bg-white/[.035] p-3"><dt className="text-white/35">{label}</dt><dd className="mt-1 break-words font-bold text-white/70">{value}</dd></div>; }
