"use client";

import { useState } from "react";
import { Bug, CheckCircle2, ChevronDown } from "lucide-react";
import { createClient } from "@/lib/supabase-browser";

export type BugReportItem = { id: number; memberName: string; category: string; detail: string; pageUrl: string | null; userAgent: string | null; status: string; createdAt: string };
const categoryLabels: Record<string, string> = { display: "表示", operation: "操作", video: "動画", data: "記録・データ", notification: "通知", other: "その他" };

export default function BugReportManager({ initialItems }: { initialItems: BugReportItem[] }) {
  const [items, setItems] = useState(initialItems); const [open, setOpen] = useState(false); const [savingId, setSavingId] = useState<number | null>(null); const pending = items.filter((item) => item.status === "pending");
  async function resolve(id: number) { setSavingId(id); const { error } = await createClient().from("bug_reports").update({ status: "resolved", resolved_at: new Date().toISOString() }).eq("id", id); setSavingId(null); if (error) { alert(error.message); return; } setItems((current) => current.map((item) => item.id === id ? { ...item, status: "resolved" } : item)); }
  return <section className="mt-8 overflow-hidden rounded-2xl border border-white/10 bg-[#111]"><button type="button" onClick={() => setOpen((current) => !current)} className="flex w-full items-center gap-3 p-5 text-left"><span className="grid h-10 w-10 place-items-center rounded-xl bg-red-500/15 text-red-300"><Bug size={19} /></span><span><strong className="block">不具合報告</strong><span className="text-xs text-white/40">会員から届いた報告を確認</span></span>{pending.length > 0 && <span className="ml-auto rounded-full bg-red-500 px-2.5 py-1 text-xs font-black">未対応 {pending.length}件</span>}<ChevronDown className={`${pending.length ? "" : "ml-auto"} text-white/40 transition ${open ? "rotate-180" : ""}`} /></button>{open && <div className="divide-y divide-white/10 border-t border-white/10 px-5">{items.map((item) => <article key={item.id} className={`py-4 ${item.status === "resolved" ? "opacity-45" : ""}`}><div className="flex flex-wrap items-center gap-2"><strong>{item.memberName}</strong><span className="rounded-full bg-white/[0.07] px-2 py-1 text-[10px] text-white/60">{categoryLabels[item.category] ?? item.category}</span><span className="text-xs text-white/35">{new Date(item.createdAt).toLocaleString("ja-JP")}</span>{item.status === "resolved" && <span className="ml-auto text-xs font-bold text-emerald-300">対応済み</span>}</div><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-white/70">{item.detail}</p>{item.pageUrl && <p className="mt-2 break-all text-xs text-white/30">発生ページ：{item.pageUrl}</p>}{item.userAgent && <details className="mt-2 text-xs text-white/30"><summary className="cursor-pointer">端末情報を見る</summary><p className="mt-1 break-all">{item.userAgent}</p></details>}{item.status === "pending" && <button type="button" disabled={savingId === item.id} onClick={() => resolve(item.id)} className="mt-3 inline-flex items-center gap-1.5 rounded-lg border border-emerald-500/30 px-3 py-2 text-xs font-bold text-emerald-300 disabled:opacity-50"><CheckCircle2 size={14} />対応済みにする</button>}</article>)}{items.length === 0 && <p className="py-8 text-center text-sm text-white/40">不具合報告はありません。</p>}</div>}</section>;
}
