"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { Megaphone, Send } from "lucide-react";
import { createClient } from "@/lib/supabase-browser";
import { programClasses } from "@/lib/program-classes";

export default function CoachAnnouncementForm() {
  const router = useRouter(); const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false);
  const [title, setTitle] = useState(""); const [body, setBody] = useState(""); const [audience, setAudience] = useState("all"); const [programClass, setProgramClass] = useState("ジュニア"); const [important, setImportant] = useState(false); const [publishOnHome, setPublishOnHome] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); const supabase = createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) return; const resolvedAudience = publishOnHome ? "all" : audience; const notification = { title: title.trim(), body: body.trim(), audience: resolvedAudience, programClass: resolvedAudience === "class" ? programClass : null }; const { error } = await supabase.from("announcements").insert({ author_id: user.id, title: notification.title, body: notification.body, audience: notification.audience, program_class: notification.programClass, priority: important ? "important" : "normal", is_public: publishOnHome }); setSaving(false); if (error) { alert(error.message); return; } if (important) fetch("/api/push/send", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ kind: "announcement", ...notification }) }).catch(() => undefined); setTitle(""); setBody(""); setImportant(false); setPublishOnHome(false); setOpen(false); router.refresh(); }
  if (!open) return <button type="button" onClick={() => setOpen(true)} className="mt-8 inline-flex items-center gap-2 rounded-xl bg-orange-500 px-5 py-3 text-sm font-black"><Megaphone size={17} />お知らせを作成</button>;
  return <form onSubmit={submit} className="mt-8 rounded-2xl border border-orange-500/30 bg-[#111] p-5"><h2 className="font-black">お知らせを作成</h2><input value={title} onChange={(event) => setTitle(event.target.value)} required maxLength={100} placeholder="タイトル" className="mt-4 w-full rounded-lg border border-white/15 bg-black/30 px-4 py-3 outline-none focus:border-orange-500" /><textarea value={body} onChange={(event) => setBody(event.target.value)} required maxLength={2000} rows={4} placeholder="お知らせ内容" className="mt-3 w-full resize-none rounded-lg border border-white/15 bg-black/30 px-4 py-3 outline-none focus:border-orange-500" /><div className="mt-3 grid gap-3 sm:grid-cols-2"><select value={publishOnHome ? "all" : audience} disabled={publishOnHome} onChange={(event) => setAudience(event.target.value)} className="rounded-lg border border-white/15 bg-[#111] px-3 py-3 disabled:text-white/35"><option value="all">全会員</option><option value="class">クラス指定</option></select>{!publishOnHome && audience === "class" && <select value={programClass} onChange={(event) => setProgramClass(event.target.value)} className="rounded-lg border border-white/15 bg-[#111] px-3 py-3">{programClasses.map((item) => <option key={item}>{item}</option>)}</select>}</div><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="flex items-center gap-2 rounded-xl border border-white/10 p-3 text-sm text-white/60"><input type="checkbox" checked={important} onChange={(event) => setImportant(event.target.checked)} />重要なお知らせ</label><label className="flex items-center gap-2 rounded-xl border border-orange-500/30 bg-orange-500/[0.06] p-3 text-sm font-bold text-orange-300"><input type="checkbox" checked={publishOnHome} onChange={(event) => setPublishOnHome(event.target.checked)} />一般向けHOMEにも掲載</label></div>{publishOnHome ? <p className="mt-3 text-xs leading-5 text-orange-200/70">未ログインの方にも公開されます。体験会・募集・活動報告など、個人情報を含まない内容だけ掲載してください。</p> : null}<div className="mt-4 flex justify-end gap-2"><button type="button" onClick={() => setOpen(false)} className="rounded-lg border border-white/15 px-4 py-2 text-sm text-white/60">キャンセル</button><button disabled={saving} className="inline-flex items-center gap-2 rounded-lg bg-orange-500 px-4 py-2 text-sm font-black"><Send size={15} />{saving ? "送信中" : publishOnHome ? "会員＋HOMEへ配信" : "会員へ配信"}</button></div></form>;
}
