"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { Megaphone, Send } from "lucide-react";
import { createClient } from "@/lib/supabase-browser";
import { programClasses } from "@/lib/program-classes";

export default function CoachAnnouncementForm() {
  const router = useRouter(); const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false);
  const [title, setTitle] = useState(""); const [body, setBody] = useState(""); const [audience, setAudience] = useState("all"); const [programClass, setProgramClass] = useState("ジュニア"); const [important, setImportant] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); const supabase = createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) return; const { error } = await supabase.from("announcements").insert({ author_id: user.id, title: title.trim(), body: body.trim(), audience, program_class: audience === "class" ? programClass : null, priority: important ? "important" : "normal" }); setSaving(false); if (error) { alert(error.message); return; } setTitle(""); setBody(""); setOpen(false); router.refresh(); }
  if (!open) return <button type="button" onClick={() => setOpen(true)} className="mt-8 inline-flex items-center gap-2 rounded-xl bg-orange-500 px-5 py-3 text-sm font-black"><Megaphone size={17} />お知らせを作成</button>;
  return <form onSubmit={submit} className="mt-8 rounded-2xl border border-orange-500/30 bg-[#111] p-5"><h2 className="font-black">お知らせを作成</h2><input value={title} onChange={(event) => setTitle(event.target.value)} required maxLength={100} placeholder="タイトル" className="mt-4 w-full rounded-lg border border-white/15 bg-black/30 px-4 py-3 outline-none focus:border-orange-500" /><textarea value={body} onChange={(event) => setBody(event.target.value)} required maxLength={2000} rows={4} placeholder="お知らせ内容" className="mt-3 w-full resize-none rounded-lg border border-white/15 bg-black/30 px-4 py-3 outline-none focus:border-orange-500" /><div className="mt-3 grid gap-3 sm:grid-cols-2"><select value={audience} onChange={(event) => setAudience(event.target.value)} className="rounded-lg border border-white/15 bg-[#111] px-3 py-3"><option value="all">全会員</option><option value="class">クラス指定</option></select>{audience === "class" && <select value={programClass} onChange={(event) => setProgramClass(event.target.value)} className="rounded-lg border border-white/15 bg-[#111] px-3 py-3">{programClasses.map((item) => <option key={item}>{item}</option>)}</select>}</div><label className="mt-4 flex items-center gap-2 text-sm text-white/60"><input type="checkbox" checked={important} onChange={(event) => setImportant(event.target.checked)} />重要なお知らせ</label><div className="mt-4 flex justify-end gap-2"><button type="button" onClick={() => setOpen(false)} className="rounded-lg border border-white/15 px-4 py-2 text-sm text-white/60">キャンセル</button><button disabled={saving} className="inline-flex items-center gap-2 rounded-lg bg-orange-500 px-4 py-2 text-sm font-black"><Send size={15} />{saving ? "送信中" : "配信"}</button></div></form>;
}
