"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { ChevronLeft, ChevronRight, MessageCircleQuestion } from "lucide-react";
import { programClasses } from "@/lib/program-classes";

export type FeedbackQueueItem = { id: number; recordId: number | null; videoRequestId?: number | null; athleteId: string; athleteName: string; programClass: string | null; category: string; value: number | string; requestType: string; message: string | null; priority: string; status: string; createdAt: string; answeredAt: string | null };
const requestLabels: Record<string, string> = { video: "動画", movement: "動作", awareness: "意識", improvement: "改善点", other: "その他" };
const pageSize = 10;

export default function FeedbackRequestQueue({ items }: { items: FeedbackQueueItem[] }) {
  const [status, setStatus] = useState("pending"); const [programClass, setProgramClass] = useState("all"); const [priority, setPriority] = useState("all"); const [sort, setSort] = useState("oldest"); const [page, setPage] = useState(1);
  const filtered = useMemo(() => items.filter((item) => item.status === status && (programClass === "all" || item.programClass === programClass) && (priority === "all" || item.priority === priority)).sort((a, b) => { if (status === "pending" && a.priority !== b.priority) return a.priority === "urgent" ? -1 : 1; const difference = new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime(); return sort === "oldest" ? difference : -difference; }), [items, status, programClass, priority, sort]);
  const pages = Math.max(1, Math.ceil(filtered.length / pageSize)); const safePage = Math.min(page, pages); const visible = filtered.slice((safePage - 1) * pageSize, safePage * pageSize); const pendingCount = items.filter((item) => item.status === "pending").length;
  function change(setter: (value: string) => void, value: string) { setter(value); setPage(1); }
  return <section className="mt-8 rounded-2xl border border-sky-500/25 bg-sky-500/[0.04] p-5"><div className="flex items-center justify-between gap-3"><div><h2 className="flex items-center gap-2 font-black"><MessageCircleQuestion className="text-sky-400" size={19} />フィードバック依頼</h2><p className="mt-1 text-xs text-white/40">10件ずつ表示・大会前依頼を優先</p></div><span className="rounded-full bg-sky-500 px-2.5 py-1 text-xs font-black text-black">未回答 {pendingCount}件</span></div>
    <div className="mt-4 grid grid-cols-2 gap-2 lg:grid-cols-4"><select value={status} onChange={(e) => change(setStatus, e.target.value)} className="rounded-lg border border-white/15 bg-[#111] px-3 py-2 text-xs"><option value="pending">未回答</option><option value="answered">回答済み</option></select><select value={programClass} onChange={(e) => change(setProgramClass, e.target.value)} className="rounded-lg border border-white/15 bg-[#111] px-3 py-2 text-xs"><option value="all">全クラス</option>{programClasses.map((item) => <option key={item}>{item}</option>)}</select><select value={priority} onChange={(e) => change(setPriority, e.target.value)} className="rounded-lg border border-white/15 bg-[#111] px-3 py-2 text-xs"><option value="all">すべての優先度</option><option value="urgent">大会前のみ</option><option value="normal">通常のみ</option></select><select value={sort} onChange={(e) => change(setSort, e.target.value)} className="rounded-lg border border-white/15 bg-[#111] px-3 py-2 text-xs"><option value="oldest">古い順</option><option value="newest">新しい順</option></select></div>
    {visible.length ? <div className="mt-4 divide-y divide-white/10">{visible.map((item) => <Link key={`${item.videoRequestId ? "video" : "record"}-${item.id}`} href={item.videoRequestId ? `/coach/video-feedback/${item.videoRequestId}` : `/coach/athletes/${item.athleteId}?request=${item.recordId}#request-record-${item.recordId}`} className="flex items-center gap-3 py-4 first:pt-0 last:pb-0"><span className={`h-2.5 w-2.5 shrink-0 rounded-full ${item.status === "answered" ? "bg-emerald-400" : item.priority === "urgent" ? "bg-red-400" : "bg-sky-400"}`} /><span className="min-w-0 flex-1"><strong className="block text-sm">{item.athleteName}・{item.category}{item.value !== "" ? ` ${item.value}` : ""}</strong><span className="mt-1 block truncate text-xs text-white/45">{item.programClass ?? "クラス未設定"}・{item.videoRequestId ? "動画のみ" : requestLabels[item.requestType]}{item.message ? `：${item.message}` : ""}</span></span><ChevronRight size={17} className="text-sky-400" /></Link>)}</div> : <p className="mt-5 text-sm text-white/35">該当する依頼はありません</p>}
    {pages > 1 && <div className="mt-5 flex items-center justify-center gap-4 border-t border-white/10 pt-4"><button type="button" disabled={safePage === 1} onClick={() => setPage(safePage - 1)} className="p-2 text-white/60 disabled:opacity-20"><ChevronLeft size={18} /></button><span className="text-xs text-white/45">{safePage}／{pages}ページ（{filtered.length}件）</span><button type="button" disabled={safePage === pages} onClick={() => setPage(safePage + 1)} className="p-2 text-white/60 disabled:opacity-20"><ChevronRight size={18} /></button></div>}
  </section>;
}
