"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ChevronLeft, ChevronRight, LoaderCircle, MessageCircleQuestion } from "lucide-react";
import { programClasses } from "@/lib/program-classes";

export type FeedbackQueueItem = { id: number; recordId: number | null; videoRequestId?: number | null; athleteId: string; athleteName: string; programClass: string | null; category: string; value: number | string; requestType: string; message: string | null; priority: string; status: string; createdAt: string; answeredAt: string | null };
const requestLabels: Record<string, string> = { video: "動画", movement: "動作", awareness: "意識", improvement: "改善点", other: "その他" };
const pageSize = 10;

export default function FeedbackRequestQueue({ initialItems, initialTotalCount }: { initialItems: FeedbackQueueItem[]; initialTotalCount: number }) {
  const [items, setItems] = useState(initialItems); const [totalCount, setTotalCount] = useState(initialTotalCount);
  const [status, setStatus] = useState("pending"); const [programClass, setProgramClass] = useState("all"); const [priority, setPriority] = useState("all"); const [sort, setSort] = useState("oldest"); const [page, setPage] = useState(1);
  const [loading, setLoading] = useState(false); const [firstLoad, setFirstLoad] = useState(true);
  useEffect(() => {
    if (firstLoad && status === "pending" && programClass === "all" && priority === "all" && sort === "oldest" && page === 1) { setFirstLoad(false); return; }
    const controller = new AbortController(); const params = new URLSearchParams({ status, class: programClass, priority, sort, page: String(page) }); setLoading(true);
    fetch(`/api/coach/feedback-queue?${params}`, { signal: controller.signal }).then((response) => response.ok ? response.json() : Promise.reject(new Error("取得に失敗しました"))).then((result) => { setItems(result.items); setTotalCount(result.totalCount); }).catch((error) => { if (error.name !== "AbortError") setItems([]); }).finally(() => { if (!controller.signal.aborted) setLoading(false); });
    return () => controller.abort();
  }, [firstLoad, page, priority, programClass, sort, status]);
  const pages = Math.max(1, Math.ceil(totalCount / pageSize)); function change(setter: (value: string) => void, value: string) { setter(value); setPage(1); }
  return <section className="mt-8 rounded-2xl border border-sky-500/25 bg-sky-500/[0.04] p-5"><div className="flex items-center justify-between gap-3"><div><h2 className="flex items-center gap-2 font-black"><MessageCircleQuestion className="text-sky-400" size={19} />フィードバック依頼</h2><p className="mt-1 text-xs text-white/40">必要な10件だけ取得・大会前依頼を優先</p></div><span className="rounded-full bg-sky-500 px-2.5 py-1 text-xs font-black text-black">{status === "pending" ? "未回答" : "回答済み"} {totalCount}件</span></div>
    <div className="mt-4 grid grid-cols-2 gap-2 lg:grid-cols-4"><select value={status} onChange={(e) => change(setStatus, e.target.value)} className="rounded-lg border border-white/15 bg-[#111] px-3 py-2 text-xs"><option value="pending">未回答</option><option value="answered">回答済み</option></select><select value={programClass} onChange={(e) => change(setProgramClass, e.target.value)} className="rounded-lg border border-white/15 bg-[#111] px-3 py-2 text-xs"><option value="all">全クラス</option>{programClasses.map((item) => <option key={item}>{item}</option>)}</select><select value={priority} onChange={(e) => change(setPriority, e.target.value)} className="rounded-lg border border-white/15 bg-[#111] px-3 py-2 text-xs"><option value="all">すべての優先度</option><option value="urgent">大会前のみ</option><option value="normal">通常のみ</option></select><select value={sort} onChange={(e) => change(setSort, e.target.value)} className="rounded-lg border border-white/15 bg-[#111] px-3 py-2 text-xs"><option value="oldest">古い順</option><option value="newest">新しい順</option></select></div>
    <div className="relative min-h-20">{loading && <div className="absolute inset-0 z-10 grid place-items-center rounded-xl bg-[#0b1115]/75"><LoaderCircle size={22} className="animate-spin text-sky-400" /></div>}{items.length ? <div className="mt-4 divide-y divide-white/10">{items.map((item) => <Link key={`${item.videoRequestId ? "video" : "record"}-${item.id}`} href={item.videoRequestId ? `/coach/video-feedback/${item.videoRequestId}` : `/coach/athletes/${item.athleteId}?request=${item.recordId}#request-record-${item.recordId}`} className="flex items-center gap-3 py-4 first:pt-0 last:pb-0"><span className={`h-2.5 w-2.5 shrink-0 rounded-full ${item.status === "answered" ? "bg-emerald-400" : item.priority === "urgent" ? "bg-red-400" : "bg-sky-400"}`} /><span className="min-w-0 flex-1"><strong className="block text-sm">{item.athleteName}・{item.category}{item.value !== "" ? ` ${item.value}` : ""}</strong><span className="mt-1 block truncate text-xs text-white/45">{item.programClass ?? "クラス未設定"}・{item.videoRequestId ? "動画のみ" : requestLabels[item.requestType]}{item.message ? `：${item.message}` : ""}</span></span><ChevronRight size={17} className="text-sky-400" /></Link>)}</div> : !loading && <p className="mt-5 text-sm text-white/35">該当する依頼はありません</p>}</div>
    {pages > 1 && <div className="mt-5 flex items-center justify-center gap-4 border-t border-white/10 pt-4"><button type="button" disabled={page === 1 || loading} onClick={() => setPage(page - 1)} className="p-2 text-white/60 disabled:opacity-20"><ChevronLeft size={18} /></button><span className="text-xs text-white/45">{page}／{pages}ページ（{totalCount}件）</span><button type="button" disabled={page === pages || loading} onClick={() => setPage(page + 1)} className="p-2 text-white/60 disabled:opacity-20"><ChevronRight size={18} /></button></div>}
  </section>;
}
