"use client";

import { FormEvent, useState } from "react";
import { MessageCircleQuestion, Send, X } from "lucide-react";
import { createClient } from "@/lib/supabase-browser";

type RequestItem = { id: number; request_type: string; message: string | null; priority: string; status: string };
const labels: Record<string, string> = { video: "動画を見てほしい", movement: "動作について", awareness: "意識の方向性", improvement: "次回の改善点", other: "その他" };

export default function FeedbackRequestButton({ recordId, initialRequest }: { recordId: number; initialRequest?: RequestItem | null }) {
  const [request, setRequest] = useState(initialRequest ?? null); const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false); const [type, setType] = useState("video"); const [message, setMessage] = useState(""); const [urgent, setUrgent] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); const { data, error } = await createClient().from("feedback_requests").insert({ record_id: recordId, request_type: type, message: message.trim() || null, priority: urgent ? "urgent" : "normal" }).select("id, request_type, message, priority, status").single(); setSaving(false); if (error) { alert(error.message); return; } setRequest(data); setOpen(false); }
  async function cancel() { if (!request || !confirm("フィードバック依頼を取り消しますか？")) return; const { error } = await createClient().from("feedback_requests").update({ status: "cancelled" }).eq("id", request.id); if (error) { alert(error.message); return; } setRequest(null); }
  if (request?.status === "pending") return <div className="mt-4 rounded-xl border border-sky-500/25 bg-sky-500/[0.07] p-3"><div className="flex items-center justify-between gap-3"><div><span className="text-xs font-black text-sky-300">フィードバック依頼中{request.priority === "urgent" ? "・大会前" : ""}</span><p className="mt-1 text-xs text-white/55">{labels[request.request_type]}{request.message ? `：${request.message}` : ""}</p></div><button type="button" onClick={cancel} aria-label="依頼を取り消す" className="p-2 text-white/40"><X size={15} /></button></div></div>;
  if (!open) return <button type="button" onClick={() => setOpen(true)} className="mt-4 inline-flex items-center gap-2 rounded-lg border border-sky-500/35 px-4 py-2 text-sm font-bold text-sky-300"><MessageCircleQuestion size={15} />コーチにフィードバックを依頼</button>;
  return <form onSubmit={submit} className="mt-4 rounded-xl border border-sky-500/25 bg-sky-500/[0.05] p-4"><label className="text-xs font-black text-sky-300">特に見てほしいこと</label><select value={type} onChange={(e) => setType(e.target.value)} className="mt-3 w-full rounded-lg border border-white/15 bg-[#111] px-3 py-3 text-sm">{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><textarea value={message} onChange={(e) => setMessage(e.target.value)} maxLength={500} rows={2} placeholder="質問や気になる点（任意）" className="mt-3 w-full resize-none rounded-lg border border-white/15 bg-black/30 px-3 py-3 text-sm" /><label className="mt-3 flex items-center gap-2 text-xs text-white/60"><input type="checkbox" checked={urgent} onChange={(e) => setUrgent(e.target.checked)} />大会前など、早めに見てほしい</label><div className="mt-3 flex justify-end gap-2"><button type="button" onClick={() => setOpen(false)} className="rounded-lg border border-white/15 px-3 py-2 text-xs">キャンセル</button><button disabled={saving} className="inline-flex items-center gap-2 rounded-lg bg-sky-500 px-3 py-2 text-xs font-black text-black"><Send size={13} />{saving ? "送信中" : "依頼する"}</button></div></form>;
}
