"use client";

import { useEffect, useMemo, useState } from "react";
import { Check, Cloud, LoaderCircle, RotateCcw, Save } from "lucide-react";
import { competitionDetailMode, eventNamesByKind, isWindAffectedEvent, unitMap, type PerformanceKind } from "@/lib/performance-events";
import { bestCompetitionDetail, type CompetitionDetailInput } from "@/lib/competition-details";
import CompetitionDetailEditor from "@/app/components/CompetitionDetailEditor";

type Athlete={id:string;name:string;programClass:string|null;event:string|null};
type Schedule={id:number;title:string;startsAt:string;type:string|null;programClass:string|null;attendeeIds:string[]};
type Entry={value?:string;wind?:string;details?:CompetitionDetailInput[]};
const storageKey="vaultex-performance-live-v1";
const scheduleYear = (startsAt:string) => Number(new Date(startsAt).toLocaleDateString("en-CA",{year:"numeric",timeZone:"Asia/Tokyo"}));

export default function PerformanceSession({athletes,schedules}:{athletes:Athlete[];schedules:Schedule[]}) {
  const [kind,setKind]=useState<Extract<PerformanceKind,"athletics"|"unofficial-athletics">>("unofficial-athletics");
  const [category,setCategory]=useState(eventNamesByKind("unofficial-athletics")[0]);
  const [scheduleId,setScheduleId]=useState(""); const [programClass,setProgramClass]=useState("all");
  const [year,setYear]=useState(()=>Number(new Date().toLocaleDateString("en-CA",{year:"numeric",timeZone:"Asia/Tokyo"})));
  const [date,setDate]=useState(()=>new Date().toLocaleDateString("en-CA",{timeZone:"Asia/Tokyo"}));
  const [entries,setEntries]=useState<Record<string,Entry>>({}); const [restored,setRestored]=useState(false);
  const [saving,setSaving]=useState(false); const [message,setMessage]=useState("");
  useEffect(()=>{const frame=requestAnimationFrame(()=>{try{const raw=localStorage.getItem(storageKey);if(raw){const draft=JSON.parse(raw);setKind(draft.kind??"unofficial-athletics");setCategory(draft.category??eventNamesByKind("unofficial-athletics")[0]);setEntries(draft.entries??{});if(draft.date)setDate(draft.date);setScheduleId(draft.scheduleId??"");setProgramClass(draft.programClass??"all");if(Number.isInteger(draft.year))setYear(draft.year);}}finally{setRestored(true);}});return()=>cancelAnimationFrame(frame);},[]);
  useEffect(()=>{if(restored)localStorage.setItem(storageKey,JSON.stringify({kind,category,entries,date,scheduleId,programClass,year}));},[kind,category,entries,date,scheduleId,programClass,year,restored]);
  const years=useMemo(()=>[...new Set([year,...schedules.map((schedule)=>scheduleYear(schedule.startsAt))])].sort((a,b)=>b-a),[schedules,year]);
  const yearSchedules=useMemo(()=>schedules.filter((schedule)=>scheduleYear(schedule.startsAt)===year),[schedules,year]);
  const selectedSchedule=schedules.find((s)=>String(s.id)===scheduleId);
  const roster=useMemo(()=>athletes.filter((a)=>selectedSchedule?selectedSchedule.attendeeIds.includes(a.id):programClass==="all"||a.programClass===programClass),[athletes,selectedSchedule,programClass]);
  const needsWind=kind==="athletics"&&isWindAffectedEvent(category); const unit=unitMap[category]??"";
  const detailMode=kind==="athletics"?competitionDetailMode(category):null;
  const setEntry=(id:string,patch:Partial<Entry>)=>setEntries((current)=>({...current,[id]:{...(current[id]??{}),...patch}}));
  const representative=(entry?:Entry)=>entry?.details?.length&&detailMode?bestCompetitionDetail(entry.details,detailMode==="round"):{numericValue:Number(entry?.value),windSpeed:entry?.wind};
  const count=roster.filter((a)=>{const best=representative(entries[a.id]);return best&&Number.isFinite(best.numericValue)&&best.numericValue>0;}).length;
  const enableDetails=(id:string)=>setEntry(id,{details:detailMode==="attempt"?Array.from({length:6},(_,index)=>({sequenceNumber:index+1,value:"",windSpeed:"",status:"valid" as const})):[{sequenceNumber:1,roundName:"予選",value:"",windSpeed:"",place:"",status:"valid"}]});
  function changeKind(next:typeof kind){setKind(next);setCategory(eventNamesByKind(next)[0]);setEntries({});setMessage("");}
  async function publish(){const records=roster.flatMap((athlete)=>{const entry=entries[athlete.id];const best=representative(entry);const value=Number(best?.numericValue);if(!Number.isFinite(value)||value<=0)return[];return[{athleteId:athlete.id,value,windSpeed:best?.windSpeed?.trim()?Number(best.windSpeed):null,details:entry?.details??[]}];});if(!records.length){setMessage("記録を1件以上入力してください。");return;}if(!confirm(`${records.length}名の${kind==="athletics"?"本番":"練習"}記録を反映します。よろしいですか？`))return;setSaving(true);setMessage("");try{const response=await fetch("/api/coach/performance-session",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({kind,category,date,scheduleId:scheduleId||null,records})});const result=await response.json();if(!response.ok)throw new Error(result.error??"保存できませんでした。");setEntries({});localStorage.removeItem(storageKey);setMessage(`${result.saved}件を反映しました。${result.skipped?` 入力済み${result.skipped}件は重複を避けてスキップしました。`:""}`);}catch(error){setMessage(error instanceof Error?error.message:"保存できませんでした。");}finally{setSaving(false);}}
  return <div className="mt-8 space-y-5">
    <div className="grid grid-cols-2 gap-2 rounded-2xl border border-white/10 bg-[#111] p-2"><button onClick={()=>changeKind("unofficial-athletics")} className={`rounded-xl px-4 py-4 text-sm font-black ${kind==="unofficial-athletics"?"bg-orange-500 text-black":"text-white/45"}`}>通常練習</button><button onClick={()=>changeKind("athletics")} className={`rounded-xl px-4 py-4 text-sm font-black ${kind==="athletics"?"bg-orange-500 text-black":"text-white/45"}`}>大会記録</button></div>
    <section className="grid gap-3 rounded-3xl border border-white/10 bg-[#111] p-4 sm:grid-cols-2 lg:grid-cols-5 sm:p-6"><label className="text-xs font-bold text-white/55">実施日<input type="date" value={date} onChange={(e)=>setDate(e.target.value)} className="mt-2 w-full rounded-xl border border-white/15 bg-black/30 px-4 py-3 text-white [color-scheme:dark]"/></label><label className="text-xs font-bold text-white/55">種目<select value={category} onChange={(e)=>{setCategory(e.target.value);setEntries({});}} className="mt-2 w-full rounded-xl border border-white/15 bg-[#0b0c0e] px-4 py-3 text-white">{eventNamesByKind(kind).map((name)=><option key={name}>{name}</option>)}</select></label><label className="text-xs font-bold text-white/55">予定の年<select value={year} onChange={(e)=>{setYear(Number(e.target.value));setScheduleId("");}} className="mt-2 w-full rounded-xl border border-white/15 bg-[#0b0c0e] px-4 py-3 text-white">{years.map((item)=><option key={item} value={item}>{item}年</option>)}</select></label><label className="text-xs font-bold text-white/55">参加名簿<select value={scheduleId} onChange={(e)=>setScheduleId(e.target.value)} className="mt-2 w-full rounded-xl border border-white/15 bg-[#0b0c0e] px-4 py-3 text-white"><option value="">クラスから選ぶ</option>{yearSchedules.map((s)=><option key={s.id} value={s.id}>{new Date(s.startsAt).toLocaleDateString("ja-JP",{timeZone:"Asia/Tokyo"})} {s.title}（参加{s.attendeeIds.length}名）</option>)}</select></label><label className="text-xs font-bold text-white/55">クラス<select disabled={!!scheduleId} value={programClass} onChange={(e)=>setProgramClass(e.target.value)} className="mt-2 w-full rounded-xl border border-white/15 bg-[#0b0c0e] px-4 py-3 text-white disabled:opacity-40"><option value="all">全選手</option>{["ジュニア","ユース","エリート","マスターズ"].map((c)=><option key={c}>{c}</option>)}</select></label></section>
    <section className="overflow-hidden rounded-3xl border border-orange-500/35 bg-[#101010]"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-white/10 p-5"><div><p className="text-[10px] font-black tracking-[.16em] text-orange-400">{kind==="athletics"?"COMPETITION":"TRAINING"}</p><h2 className="mt-1 text-2xl font-black">{category}</h2><p className="mt-1 text-xs text-white/45">コーチが記録を先に入力。振り返りは選手があとから追加できます。</p></div><span className="flex items-center gap-2 text-xs text-emerald-300"><Cloud size={15}/>端末へ自動保存</span></div><div className="divide-y divide-white/[.07]">{roster.length?roster.map((athlete)=>{const entry=entries[athlete.id]??{};return <div key={athlete.id} className="p-4"><div className={`grid gap-3 ${needsWind?"sm:grid-cols-[minmax(190px,1fr)_180px_180px]":"sm:grid-cols-[minmax(190px,1fr)_220px]"} sm:items-center`}><div><strong>{athlete.name}</strong><span className="ml-2 text-xs text-white/35">{athlete.programClass}</span><p className="mt-1 text-[11px] text-white/35">{athlete.event}</p></div>{!entry.details?.length?<><label className="relative"><input aria-label={`${athlete.name} 記録`} inputMode="decimal" placeholder="記録" value={entry.value??""} onChange={(e)=>setEntry(athlete.id,{value:e.target.value})} className="w-full rounded-xl border border-white/15 bg-black/30 px-3 py-3 pr-14 text-lg font-black outline-none focus:border-orange-500"/><span className="absolute right-3 top-3.5 text-xs text-white/35">{unit}</span></label>{needsWind&&<label className="relative"><input aria-label={`${athlete.name} 風速`} inputMode="decimal" placeholder="風速" value={entry.wind??""} onChange={(e)=>setEntry(athlete.id,{wind:e.target.value})} className="w-full rounded-xl border border-white/15 bg-black/30 px-3 py-3 pr-14 text-lg font-black outline-none focus:border-orange-500"/><span className="absolute right-3 top-3.5 text-xs text-white/35">m/s</span></label>}</>:<div className="sm:col-span-2 text-sm font-black text-emerald-300">代表記録 {representative(entry)?.numericValue ?? "—"}{unit}</div>}</div>{detailMode?<div className="mt-3">{entry.details?.length?<><CompetitionDetailEditor mode={detailMode} details={entry.details} onChange={(details)=>setEntry(athlete.id,{details})} unit={unit} needsWind={needsWind}/><button type="button" onClick={()=>setEntry(athlete.id,{details:undefined})} className="mt-2 text-xs text-white/40">通常入力に戻す</button></>:<button type="button" onClick={()=>enableDetails(athlete.id)} className="rounded-lg border border-orange-500/30 px-3 py-2 text-xs font-black text-orange-300">{detailMode==="attempt"?"1〜6回を入力":"予選・決勝などを入力"}</button>}</div>:null}</div>}):<p className="p-10 text-center text-sm text-white/35">参加者がいません。予定の出欠またはクラスを確認してください。</p>}</div></section>
    <div className="sticky bottom-3 z-20 flex flex-wrap items-center gap-3 rounded-2xl border border-orange-500/30 bg-[#111]/95 p-3 shadow-2xl backdrop-blur"><span className="mr-auto text-sm font-bold">入力済み {count}/{roster.length}名</span><button onClick={()=>{if(confirm("入力途中の内容を消しますか？")){setEntries({});localStorage.removeItem(storageKey);}}} className="inline-flex items-center gap-2 rounded-xl border border-white/15 px-4 py-3 text-xs font-bold text-white/55"><RotateCcw size={15}/>下書きを消す</button><button disabled={saving} onClick={publish} className="inline-flex items-center gap-2 rounded-xl bg-orange-500 px-5 py-3 text-sm font-black text-black disabled:opacity-50">{saving?<LoaderCircle size={17} className="animate-spin"/>:<Save size={17}/>}一括反映</button></div>{message&&<p role="status" className="rounded-xl border border-orange-500/30 bg-orange-500/10 p-4 text-sm text-orange-200"><Check size={16} className="mr-2 inline"/>{message}</p>}
  </div>;
}
