import FamilyShell, { Card, SectionTitle } from "../FamilyShell";
import { loadFamilyData, requireFamilyContext } from "@/lib/family";

const fmt = (value: number | null) => value == null ? "—" : String(Math.round(value));
export default async function FamilyGrowthPage({ searchParams }: { searchParams: Promise<{ athlete?: string; month?: string }> }) {
  const { athlete, month } = await searchParams; const context = await requireFamilyContext(athlete); const data = await loadFamilyData(context, month);
  return <FamilyShell context={context} active="/family/growth"><SectionTitle eyebrow="MONTHLY GROWTH REPORT">{data.selectedMonth.replace("-","年")}月の成長レポート</SectionTitle><p className="mt-3 max-w-2xl text-sm leading-7 text-black/50">点数の優劣ではなく、前回からの変化と次の成長を見守るためのレポートです。</p>
    <div className="mt-6 grid gap-5 lg:grid-cols-2"><Card><h3 className="font-black">活動</h3><p className="mt-4 text-3xl font-black">{data.activity.sessions} SESSION <span className="text-black/20">/</span> {data.activity.classes} CLASS</p><p className="mt-3 text-sm text-black/50">PB更新 {data.activity.pbUpdates}回・CONTROL TEST {data.activity.controlTests}回</p></Card><Card><h3 className="font-black">BIGGEST GROWTH</h3><strong className="mt-4 block text-4xl text-orange-600">{data.biggestGrowth?.axis ?? "NEXT GROWTH"}</strong><p className="mt-2 text-sm text-black/50">{data.biggestGrowth?.delta != null ? `前回から ${data.biggestGrowth.delta >= 0 ? "+" : ""}${data.biggestGrowth.delta}` : "次回測定から変化が表示されます"}</p></Card></div>
    <Card className="mt-5"><SectionTitle eyebrow="ATHLETE SCAN">身体能力構成の変化</SectionTitle><p className="mt-2 text-xs leading-6 text-black/45">ATHLETE TYPEは才能や競技適性の診断ではなく、現在の身体能力構成を表すものです。</p><div className="mt-6 grid gap-4 sm:grid-cols-3">{data.growth.map((item)=><article key={item.axis} className="rounded-xl bg-[#f5f2ec] p-5"><p className="text-xs font-black tracking-[.12em]">{item.axis}</p><p className="mt-3 text-2xl font-black">{fmt(item.previous)} → {fmt(item.current)}</p><p className="mt-2 text-sm font-black text-emerald-600">{item.delta == null ? "比較データなし" : `${item.delta >= 0 ? "+" : ""}${item.delta}`}</p><p className="mt-2 text-xs text-black/40">初回 {fmt(item.first)} → 現在 {fmt(item.current)}</p></article>)}</div><div className="mt-5 grid gap-3 text-sm sm:grid-cols-3"><p><span className="block text-[10px] font-black text-black/35">CURRENT ATHLETE TYPE</span>{data.latestScan?.typeName ?? "測定準備中"}</p><p><span className="block text-[10px] font-black text-black/35">CONTACT PROFILE</span>{data.latestScan?.contactProfile ?? "測定準備中"}</p><p><span className="block text-[10px] font-black text-black/35">CONTROL TEST</span>{data.latestScan ? new Date(data.latestScan.measuredOn).toLocaleDateString("ja-JP") : "未実施"}</p></div></Card>
    <div className="mt-5 grid gap-5 lg:grid-cols-2"><Card><SectionTitle eyebrow="RECORD">主要記録の変化</SectionTitle><div className="mt-5 space-y-3">{data.recordChanges.length ? data.recordChanges.map((record)=><div key={record.category} className="flex items-center justify-between border-b border-black/8 pb-3 text-sm"><strong>{record.category}</strong><span>{record.first}{record.unit} → <b>{record.latest}{record.unit}</b></span></div>) : <p className="text-sm text-black/45">比較できる記録がたまると表示されます。</p>}</div></Card><Card><SectionTitle eyebrow="COACH MESSAGE">コーチコメント</SectionTitle><p className="mt-5 whitespace-pre-wrap text-sm leading-8 text-black/65">{data.report?.coach_message || "今月のコメントは準備中です。"}</p>{data.report?.next_month ? <div className="mt-5 rounded-xl bg-orange-50 p-4"><p className="text-[10px] font-black text-orange-700">NEXT MONTH</p><p className="mt-2 text-sm font-bold">{data.report.next_month}</p></div> : null}</Card></div>
  </FamilyShell>;
}
