import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { ArrowLeft, ClipboardCheck, Users } from "lucide-react";
import { createClient } from "@/lib/supabase-server";
import { createAdminClient } from "@/lib/supabase-admin";
import TeamClient from "./TeamClient";
import SessionHistory from "./SessionHistory";

export default async function TeamPage({params}:{params:Promise<{teamId:string}>}){const {teamId}=await params;const supabase=await createClient();const {data:auth}=await supabase.auth.getClaims();const userId=auth?.claims.sub;if(!userId)redirect(`/login?next=/scan/${teamId}`);const admin=createAdminClient();const {data:member}=await admin.from("scan_team_members").select("role,scan_teams(id,name)").eq("team_id",teamId).eq("user_id",userId).maybeSingle();if(!member)notFound();const team=member.scan_teams as unknown as {id:string;name:string};const [{data:athletes},{data:sessions}]=await Promise.all([admin.from("scan_team_athletes").select("id,name,grade,event,gender").eq("team_id",teamId).eq("active",true).order("name"),admin.from("scan_team_sessions").select("id,title,measured_on,status").eq("team_id",teamId).order("measured_on",{ascending:false}).limit(10)]);
 return <main className="px-5 pb-24 pt-28 sm:px-8"><div className="mx-auto max-w-6xl"><Link href="/scan/dashboard" className="inline-flex items-center gap-2 text-xs font-bold text-white/45"><ArrowLeft size={15}/>チーム一覧</Link><p className="mt-8 text-xs font-black tracking-[.2em] text-emerald-400">TEAM</p><h1 className="mt-2 text-4xl font-black sm:text-6xl">{team.name}</h1><TeamClient teamId={teamId}/><div className="mt-8 grid gap-6 lg:grid-cols-2"><section className="rounded-3xl border border-white/10 bg-[#0f1110] p-6"><h2 className="flex items-center gap-2 font-black"><Users className="text-emerald-400" size={19}/>選手名簿 <span className="ml-auto text-sm text-white/35">{athletes?.length??0}名</span></h2><div className="mt-5 divide-y divide-white/[.07]">{athletes?.length?athletes.map(a=><div key={a.id} className="flex items-center py-3"><strong>{a.name}</strong><span className="ml-auto text-xs text-white/35">{[a.gender==="male"?"男子":a.gender==="female"?"女子":"区分未設定",a.grade,a.event].filter(Boolean).join(" ・ ")}</span></div>):<p className="py-8 text-center text-sm text-white/30">選手を追加してください</p>}</div></section><section className="rounded-3xl border border-white/10 bg-[#0f1110] p-6"><h2 className="flex items-center gap-2 font-black"><ClipboardCheck className="text-orange-500" size={19}/>測定履歴</h2><SessionHistory teamId={teamId} sessions={sessions??[]}/></section></div></div></main>}
