"use client";
import { useState } from "react";
import { ExternalLink, LoaderCircle, Trash2 } from "lucide-react";
import { useRouter } from "next/navigation";

type Session={id:string;title:string;measured_on:string;status:string};
export default function SessionHistory({teamId,sessions}:{teamId:string;sessions:Session[]}){
 const router=useRouter();const [deleted,setDeleted]=useState<string[]>([]);const [deleting,setDeleting]=useState<string|null>(null);const [error,setError]=useState("");const visible=sessions.filter(item=>!deleted.includes(item.id));
 async function remove(session:Session){if(!window.confirm(`${session.measured_on}の測定会を削除しますか？\nこの測定会で保存した全選手の記録も削除され、元に戻せません。`))return;setDeleting(session.id);setError("");try{const response=await fetch(`/api/scan/teams/${teamId}/sessions?sessionId=${encodeURIComponent(session.id)}`,{method:"DELETE"});const result=await response.json();if(!response.ok)throw new Error(result.error);setDeleted(current=>[...current,session.id]);router.refresh();}catch(cause){setError(cause instanceof Error?cause.message:"削除できませんでした。")}finally{setDeleting(null)}}
 return <div className="mt-5 divide-y divide-white/[.07]">{error?<p className="mb-3 rounded-xl border border-red-500/30 bg-red-500/10 p-3 text-xs text-red-200">{error}</p>:null}{visible.length?visible.map(session=><div key={session.id} className="flex items-center gap-3 py-3"><div><strong>{session.measured_on}</strong><span className="ml-3 text-sm text-white/45">{session.title}</span></div><span className="ml-auto text-xs text-emerald-300">{session.status==="complete"?"完了":"下書き"}</span><a href={`/scan/${teamId}/sessions/${session.id}`} aria-label={`${session.measured_on}の詳しい結果を見る`} className="grid size-9 place-items-center rounded-lg border border-white/15 text-white/60 hover:border-orange-400 hover:text-orange-300"><ExternalLink size={15}/></a><button type="button" onClick={()=>remove(session)} disabled={deleting===session.id} aria-label={`${session.measured_on}の測定会を削除`} className="grid size-9 place-items-center rounded-lg border border-red-500/25 text-red-300 hover:bg-red-500/10 disabled:opacity-40">{deleting===session.id?<LoaderCircle className="animate-spin" size={15}/>:<Trash2 size={15}/>}</button></div>):<p className="py-8 text-center text-sm text-white/30">まだ測定会がありません</p>}</div>
}
