import { NextRequest, NextResponse } from "next/server";
import { createAdminClient, hasAdminKey } from "@/lib/supabase-admin";
import { controlTestByCode } from "@/lib/control-test";
import { hashParticipantPin, hashParticipantSecret, randomAccessToken } from "@/lib/scan-participant-auth";

async function getSession(code:string){const admin=createAdminClient();const {data}=await admin.from("scan_team_sessions").select("id,team_id,title,measured_on,status,selected_test_codes,scan_teams(name)").eq("join_code",code).eq("participation_mode","student").maybeSingle();return{admin,session:data};}
export async function GET(_:NextRequest,{params}:{params:Promise<{joinCode:string}>}){if(!hasAdminKey())return NextResponse.json({error:"利用できません。"},{status:503});const {joinCode}=await params;const {admin,session}=await getSession(joinCode);if(!session)return NextResponse.json({error:"測定会が見つかりません。"},{status:404});const {data:athletes}=await admin.from("scan_team_athletes").select("id,name,grade,event").eq("team_id",session.team_id).eq("active",true).order("name");return NextResponse.json({session,athletes:athletes??[]});}
export async function POST(request:NextRequest,{params}:{params:Promise<{joinCode:string}>}){if(!hasAdminKey())return NextResponse.json({error:"利用できません。"},{status:503});const {joinCode}=await params;const {admin,session}=await getSession(joinCode);if(!session)return NextResponse.json({error:"測定会が見つかりません。"},{status:404});if(session.status!=="draft")return NextResponse.json({error:"この測定会の入力は終了しています。"},{status:409});const body=await request.json() as {action?:unknown;athleteId?:unknown;pin?:unknown;token?:unknown;values?:unknown};const athleteId=typeof body.athleteId==="string"?body.athleteId:"";const {data:athlete}=await admin.from("scan_team_athletes").select("id,name").eq("id",athleteId).eq("team_id",session.team_id).eq("active",true).maybeSingle();if(!athlete)return NextResponse.json({error:"選手を確認してください。"},{status:400});
 if(body.action==="claim"){const pin=typeof body.pin==="string"?body.pin:"";if(!/^\d{4}$/.test(pin))return NextResponse.json({error:"4桁の暗証番号を入力してください。"},{status:400});const pinHash=hashParticipantPin(session.id,pin);const {data:existing}=await admin.from("scan_session_participants").select("id,pin_hash,status,draft_values").eq("session_id",session.id).eq("athlete_id",athleteId).maybeSingle();if(existing&&existing.pin_hash!==pinHash)return NextResponse.json({error:"暗証番号が違います。"},{status:403});const token=randomAccessToken();const row={session_id:session.id,team_id:session.team_id,athlete_id:athleteId,pin_hash:pinHash,access_token_hash:hashParticipantSecret(token),last_saved_at:new Date().toISOString()};const {data:participant,error}=await admin.from("scan_session_participants").upsert(row,{onConflict:"session_id,athlete_id"}).select("status,draft_values").single();if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({ok:true,token,athlete,status:participant.status,values:participant.draft_values??{}});}
 const token=typeof body.token==="string"?body.token:"";const {data:participant}=await admin.from("scan_session_participants").select("id,access_token_hash,status").eq("session_id",session.id).eq("athlete_id",athleteId).maybeSingle();if(!participant||participant.access_token_hash!==hashParticipantSecret(token))return NextResponse.json({error:"もう一度、名前と暗証番号で入り直してください。"},{status:401});if(participant.status!=="inputting")return NextResponse.json({error:"すでに提出済みです。"},{status:409});const values=body.values&&typeof body.values==="object"?body.values as Record<string,unknown>:{};const clean=Object.fromEntries(Object.entries(values).flatMap(([code,input])=>{if(!session.selected_test_codes.includes(code)||!controlTestByCode[code]||!Array.isArray(input))return[];const attempts=input.map(Number).filter(value=>Number.isFinite(value)&&value>0&&value<100000).slice(0,10);return attempts.length?[[code,attempts]]:[];}));
 const submitting=body.action==="submit";if(submitting&&!Object.keys(clean).length)return NextResponse.json({error:"記録を1件以上入力してください。"},{status:400});const {error:updateError}=await admin.from("scan_session_participants").update({draft_values:clean,last_saved_at:new Date().toISOString(),...(submitting?{status:"submitted",submitted_at:new Date().toISOString()}:{})}).eq("id",participant.id);if(updateError)return NextResponse.json({error:updateError.message},{status:500});if(submitting){const rows=Object.entries(clean).map(([code,attempts])=>{const definition=controlTestByCode[code];return{session_id:session.id,team_id:session.team_id,athlete_id:athleteId,test_code:code,primary_value:definition.betterDirection==="lower"?Math.min(...attempts):Math.max(...attempts),attempts,entered_by:null,entry_source:"student"};});const {error}=await admin.from("scan_team_measurements").upsert(rows,{onConflict:"session_id,athlete_id,test_code"});if(error){await admin.from("scan_session_participants").update({status:"inputting",submitted_at:null}).eq("id",participant.id);return NextResponse.json({error:error.message},{status:500});}}
 return NextResponse.json({ok:true,submitted:submitting});}
