import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { ArrowLeft } from "lucide-react";
import { createClient } from "@/lib/supabase-server";
import { createAdminClient } from "@/lib/supabase-admin";
import { controlTestByCode } from "@/lib/control-test";

export default async function SessionDetailPage({ params }: { params: Promise<{ teamId: string; sessionId: string }> }) {
  const { teamId, sessionId } = await params; const supabase = await createClient(); const { data: auth } = await supabase.auth.getClaims(); const userId = auth?.claims.sub; if (!userId) redirect(`/login?next=/scan/${teamId}/sessions/${sessionId}`);
  const admin = createAdminClient(); const { data: member } = await admin.from("scan_team_members").select("scan_teams(name)").eq("team_id", teamId).eq("user_id", userId).in("role", ["owner", "coach"]).maybeSingle(); if (!member) notFound();
  const [{ data: session }, { data: measurements }] = await Promise.all([admin.from("scan_team_sessions").select("id,title,measured_on,status,scan_teams(name)").eq("id", sessionId).eq("team_id", teamId).maybeSingle(), admin.from("scan_team_measurements").select("id,athlete_id,test_code,primary_value,attempts,entry_source,updated_at,scan_team_athletes(name,gender,grade)").eq("session_id", sessionId).eq("team_id", teamId).order("athlete_id").order("test_code")]);
  if (!session) notFound(); type MeasurementRow = NonNullable<typeof measurements>[number]; const grouped = new Map<string, { name: string; gender: string | null; grade: string | null; rows: MeasurementRow[] }>(); for (const row of measurements ?? []) { const athlete = row.scan_team_athletes as unknown as { name: string; gender: string | null; grade: string | null }; const current = grouped.get(row.athlete_id) ?? { name: athlete.name, gender: athlete.gender, grade: athlete.grade, rows: [] }; current.rows.push(row); grouped.set(row.athlete_id, current); }
  return <main className="px-5 pb-24 pt-28 sm:px-8"><div className="mx-auto max-w-5xl"><Link href={`/scan/${teamId}`} className="inline-flex items-center gap-2 text-xs font-bold text-white/45"><ArrowLeft size={15}/>チームへ戻る</Link><p className="mt-8 text-xs font-black tracking-[.2em] text-orange-400">MEASUREMENT DETAIL</p><h1 className="mt-2 text-4xl font-black sm:text-6xl">{session.title}</h1><p className="mt-3 text-sm text-white/40">{session.measured_on}　・　{(session.scan_teams as unknown as { name: string }).name}</p><div className="mt-8 space-y-5">{[...grouped.values()].map((athlete) => <section key={athlete.name} className="overflow-hidden rounded-3xl border border-white/10 bg-[#101311]"><header className="flex items-center gap-3 border-b border-white/10 p-5"><div><h2 className="text-xl font-black">{athlete.name}</h2><p className="text-xs text-white/35">{[athlete.gender === "male" ? "男子" : athlete.gender === "female" ? "女子" : "区分未設定", athlete.grade].filter(Boolean).join(" ・ ")}</p></div><span className="ml-auto text-xs text-emerald-300">{athlete.rows.length}種目</span></header><div className="grid gap-3 p-4 sm:grid-cols-2">{athlete.rows.map((row) => { const definition = controlTestByCode[row.test_code]; const attempts = Array.isArray(row.attempts) ? row.attempts.map(String).join(" / ") : "—"; return <div key={row.id} className="rounded-2xl border border-white/10 bg-black/20 p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-black tracking-[.12em] text-orange-400">{definition?.abilityEn ?? "CONTROL TEST"}</p><h3 className="mt-1 font-black">{definition?.category ?? row.test_code}</h3></div><strong className="text-2xl text-orange-300">{row.primary_value}<small className="ml-1 text-xs text-white/40">{definition?.unit}</small></strong></div><p className="mt-3 text-xs text-white/45">試技：{attempts}</p><p className="mt-2 text-[11px] text-white/25">{row.entry_source === "student" ? "生徒入力" : "顧問入力"}</p></div>; })}</div></section>)}{grouped.size === 0 ? <p className="rounded-3xl border border-dashed border-white/15 p-12 text-center text-sm text-white/35">まだ記録がありません。</p> : null}</div></div></main>;
}
