create table if not exists public.personal_calendar_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  schedule_id bigint references public.schedules(id) on delete set null,
  entry_date date not null,
  starts_at timestamptz,
  ends_at timestamptz,
  all_day boolean not null default true,
  entry_type text not null default 'personal_training'
    check (entry_type in ('school_practice', 'personal_training', 'competition', 'rest', 'other', 'club_schedule')),
  title text not null check (char_length(title) between 1 and 120),
  location text check (location is null or char_length(location) <= 200),
  journal text check (journal is null or char_length(journal) <= 5000),
  awareness_categories text[] not null default '{}',
  record_value numeric,
  record_unit text check (record_unit is null or char_length(record_unit) <= 20),
  performance_record_id bigint references public.performance_records(id) on delete set null,
  video_path text,
  color text not null default 'orange'
    check (color in ('orange', 'sky', 'emerald', 'violet', 'rose', 'slate')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint personal_calendar_record_value_check check (record_value is null or record_value > 0),
  constraint personal_calendar_time_check check (ends_at is null or starts_at is null or ends_at >= starts_at),
  constraint personal_calendar_awareness_check check (
    awareness_categories <@ array['リズム','力感','スタート','動作','気持ち','感覚','その他']::text[]
  ),
  unique (user_id, schedule_id)
);

alter table public.personal_calendar_entries enable row level security;

drop policy if exists "Members read own personal calendar" on public.personal_calendar_entries;
create policy "Members read own personal calendar"
on public.personal_calendar_entries for select to authenticated
using (user_id = auth.uid());

drop policy if exists "Members create own personal calendar" on public.personal_calendar_entries;
create policy "Members create own personal calendar"
on public.personal_calendar_entries for insert to authenticated
with check (
  user_id = auth.uid()
  and (schedule_id is null or exists (select 1 from public.schedules s where s.id = schedule_id))
  and (performance_record_id is null or exists (
    select 1 from public.performance_records r where r.id = performance_record_id and r.user_id = auth.uid()
  ))
);

drop policy if exists "Members update own personal calendar" on public.personal_calendar_entries;
create policy "Members update own personal calendar"
on public.personal_calendar_entries for update to authenticated
using (user_id = auth.uid())
with check (
  user_id = auth.uid()
  and (performance_record_id is null or exists (
    select 1 from public.performance_records r where r.id = performance_record_id and r.user_id = auth.uid()
  ))
);

drop policy if exists "Members delete own personal calendar" on public.personal_calendar_entries;
create policy "Members delete own personal calendar"
on public.personal_calendar_entries for delete to authenticated
using (user_id = auth.uid());

create index if not exists personal_calendar_user_date_idx
  on public.personal_calendar_entries (user_id, entry_date desc);
create index if not exists personal_calendar_schedule_idx
  on public.personal_calendar_entries (schedule_id)
  where schedule_id is not null;
create index if not exists personal_calendar_performance_idx
  on public.personal_calendar_entries (performance_record_id)
  where performance_record_id is not null;

grant select, insert, update, delete on public.personal_calendar_entries to authenticated;
grant usage, select on sequence public.personal_calendar_entries_id_seq to authenticated;
