create table if not exists public.bug_reports (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  category text not null check (category in ('display', 'operation', 'video', 'data', 'notification', 'other')),
  detail text not null check (char_length(detail) between 5 and 1000),
  page_url text,
  user_agent text,
  status text not null default 'pending' check (status in ('pending', 'resolved')),
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);
alter table public.bug_reports enable row level security;
create policy "Members create own bug reports" on public.bug_reports for insert to authenticated with check (user_id = auth.uid() and status = 'pending');
create policy "Members read own bug reports" on public.bug_reports for select to authenticated using (user_id = auth.uid() or exists (select 1 from public.user_roles r where r.user_id = auth.uid() and r.role in ('coach', 'admin')));
create policy "Coaches update bug reports" on public.bug_reports for update to authenticated using (exists (select 1 from public.user_roles r where r.user_id = auth.uid() and r.role in ('coach', 'admin'))) with check (exists (select 1 from public.user_roles r where r.user_id = auth.uid() and r.role in ('coach', 'admin')));
create index if not exists bug_reports_status_created_idx on public.bug_reports(status, created_at desc);
