create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  user_agent text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.push_subscriptions enable row level security;
create policy "Members manage own push subscriptions" on public.push_subscriptions for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

create or replace function public.get_push_targets(p_kind text, p_record_id bigint default null, p_audience text default null, p_program_class text default null)
returns table(endpoint text, p256dh text, auth text)
language sql security definer set search_path = public stable as $$
  select distinct s.endpoint, s.p256dh, s.auth
  from public.push_subscriptions s
  join public.players p on p.user_id = s.user_id
  where exists (select 1 from public.user_roles r where r.user_id = auth.uid() and r.role in ('coach', 'admin'))
    and (
      (p_kind = 'feedback' and exists (select 1 from public.performance_records pr where pr.id = p_record_id and pr.user_id = s.user_id))
      or (p_kind = 'announcement' and (p_audience = 'all' or (p_audience = 'class' and p.program_class = p_program_class)))
    );
$$;
revoke all on function public.get_push_targets(text, bigint, text, text) from public;
grant execute on function public.get_push_targets(text, bigint, text, text) to authenticated;
