create table if not exists public.video_feedback_messages (
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.video_feedback_requests(id) on delete cascade,
  sender_id uuid not null references auth.users(id) on delete cascade,
  sender_role text not null check (sender_role in ('athlete', 'coach')),
  body text not null check (char_length(body) between 1 and 1000),
  created_at timestamptz not null default now()
);

create index if not exists video_feedback_messages_request_created_idx
on public.video_feedback_messages (request_id, created_at);

alter table public.video_feedback_messages enable row level security;

create policy "Participants read video feedback messages"
on public.video_feedback_messages for select to authenticated
using (
  exists (
    select 1 from public.video_feedback_requests request
    where request.id = request_id
      and (request.user_id = auth.uid() or public.is_assigned_coach(request.user_id))
  )
);

create policy "Athletes send video feedback messages"
on public.video_feedback_messages for insert to authenticated
with check (
  sender_id = auth.uid() and sender_role = 'athlete' and exists (
    select 1 from public.video_feedback_requests request
    where request.id = request_id and request.user_id = auth.uid()
  )
);

create policy "Assigned coaches send video feedback messages"
on public.video_feedback_messages for insert to authenticated
with check (
  sender_id = auth.uid() and sender_role = 'coach' and exists (
    select 1 from public.video_feedback_requests request
    where request.id = request_id and public.is_assigned_coach(request.user_id)
  )
);

insert into public.video_feedback_messages (request_id, sender_id, sender_role, body, created_at)
select id, responded_by, 'coach', response, coalesce(responded_at, created_at)
from public.video_feedback_requests request
where response is not null and responded_by is not null
  and not exists (
    select 1 from public.video_feedback_messages message
    where message.request_id = request.id and message.sender_role = 'coach' and message.body = request.response
  );

create or replace function public.sync_video_feedback_conversation_status()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.sender_role = 'coach' then
    update public.video_feedback_requests
    set status = 'answered', response = new.body, responded_by = new.sender_id, responded_at = new.created_at
    where id = new.request_id;
  else
    update public.video_feedback_requests
    set status = 'pending'
    where id = new.request_id;
  end if;
  return new;
end; $$;

drop trigger if exists sync_video_feedback_conversation_status_trigger on public.video_feedback_messages;
create trigger sync_video_feedback_conversation_status_trigger
after insert on public.video_feedback_messages
for each row execute function public.sync_video_feedback_conversation_status();
