create table if not exists public.schedule_attendance (
  id bigint generated by default as identity primary key,
  schedule_id bigint not null references public.schedules(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  status text not null check (status in ('attending', 'absent', 'undecided')),
  comment text check (comment is null or char_length(comment) <= 200),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(schedule_id, user_id)
);
alter table public.schedule_attendance enable row level security;
create policy "Members read own schedule attendance" on public.schedule_attendance for select to authenticated
using (user_id = auth.uid() or exists (select 1 from public.schedules s where s.id = schedule_id and s.author_id = auth.uid()));
create policy "Members create own schedule attendance" on public.schedule_attendance for insert to authenticated
with check (user_id = auth.uid() and exists (select 1 from public.schedules s where s.id = schedule_id));
create policy "Members update own schedule attendance" on public.schedule_attendance for update to authenticated
using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "Members delete own schedule attendance" on public.schedule_attendance for delete to authenticated
using (user_id = auth.uid());
create index if not exists schedule_attendance_schedule_idx on public.schedule_attendance(schedule_id);
