create table if not exists public.performance_record_details (
  id bigint generated by default as identity primary key,
  performance_record_id bigint not null references public.performance_records(id) on delete cascade,
  detail_type text not null check (detail_type in ('attempt', 'round')),
  sequence_number smallint not null check (sequence_number between 1 and 6),
  round_name text,
  value numeric,
  wind_speed numeric,
  place smallint check (place is null or place > 0),
  status text not null default 'valid' check (status in ('valid', 'foul', 'pass', 'dns', 'dnf', 'dq')),
  created_at timestamptz not null default now(),
  constraint performance_record_details_value_check check (
    (status = 'valid' and value is not null and value > 0)
    or (status <> 'valid' and value is null)
  ),
  constraint performance_record_details_round_name_check check (
    (detail_type = 'attempt' and round_name is null)
    or (detail_type = 'round' and round_name in ('予選', '準決勝', '決勝', 'タイムレース', 'その他'))
  ),
  unique (performance_record_id, detail_type, sequence_number)
);

create index if not exists performance_record_details_record_idx
  on public.performance_record_details (performance_record_id, sequence_number);

alter table public.performance_record_details enable row level security;

grant select, insert, update, delete on public.performance_record_details to authenticated;
grant usage, select on sequence public.performance_record_details_id_seq to authenticated;

create policy "Athletes can read own competition details"
on public.performance_record_details for select to authenticated
using (exists (
  select 1 from public.performance_records r
  where r.id = performance_record_id and r.user_id = (select auth.uid())
));

create policy "Assigned coaches can read competition details"
on public.performance_record_details for select to authenticated
using (exists (
  select 1 from public.performance_records r
  where r.id = performance_record_id and public.is_assigned_coach(r.user_id)
));

create policy "Athletes can insert own competition details"
on public.performance_record_details for insert to authenticated
with check (exists (
  select 1 from public.performance_records r
  where r.id = performance_record_id and r.user_id = (select auth.uid())
));

create policy "Athletes can update own competition details"
on public.performance_record_details for update to authenticated
using (exists (
  select 1 from public.performance_records r
  where r.id = performance_record_id and r.user_id = (select auth.uid())
))
with check (exists (
  select 1 from public.performance_records r
  where r.id = performance_record_id and r.user_id = (select auth.uid())
));

create policy "Athletes can delete own competition details"
on public.performance_record_details for delete to authenticated
using (exists (
  select 1 from public.performance_records r
  where r.id = performance_record_id and r.user_id = (select auth.uid())
));
