-- Safely finalizes the official VAULTEX CONTROL TEST Ver.1 protocol.
-- The legacy test_code values are intentionally retained for compatibility.

update public.control_test_definitions set
  version = 2,
  category = 'Flying 30m',
  ability_name_ja = '最大疾走速度',
  ability_name_en = 'MAX SPEED',
  description = '30mの助走で加速した後、次の30m区間をどれだけ速く走れるかを測定し、高い走速度を発揮する能力を見る。',
  primary_metric_key = 'flying_30m_time',
  protocol = jsonb_build_object(
    'start_method','計測開始地点の30m手前からスタートする。','attempts','最大2本。','rest','要設定。各測定間で疲労が結果へ大きく影響しないよう十分な休息を取る。',
    'measurement_method','光電管を30m地点と60m地点に設置し、30〜60m区間を計測する。全体では60m走る。','foul_conditions','要設定','adopted_record','2本実施した場合は速い方を採用。','equipment','光電管','notes','0〜30mの加速区間データも任意で保存可能。'
  ), updated_at = now()
where test_code = 'acceleration_30m';

update public.control_test_definitions set version=2, description='一度の動作で前方向へ大きな力を発揮する能力を見る。', protocol=jsonb_build_object(
  'start_method','静止状態から両足踏切。腕振り自由。','attempts','最大2本。','rest','要設定。各測定間で疲労が結果へ大きく影響しないよう十分な休息を取る。','measurement_method','踏切線から、着地時に身体が最も後方に触れた地点まで測定する。','foul_conditions','踏切線を越えて開始した場合。','adopted_record','ベスト記録。','equipment','巻尺または距離測定器具','notes','ステーション方式で実施可能。'
), updated_at=now() where test_code='standing_long_jump';

update public.control_test_definitions set version=2, description='前方向への大きな力発揮を、連続した跳躍へつなげる能力を見る。', protocol=jsonb_build_object(
  'start_method','静止状態から両足で開始。その後の脚順と腕振りは自由。','attempts','最大2本。','rest','要設定。各測定間で疲労が結果へ大きく影響しないよう十分な休息を取る。','measurement_method','連続5回跳躍し、踏切線から最終着地で身体が最も後方に触れた地点まで測定する。','foul_conditions','踏切線を越えて開始した場合。','adopted_record','ベスト記録。','equipment','巻尺または距離測定器具','notes','立三段跳・助走付き三段跳は将来候補で、Ver.1の必須種目には含めない。'
), updated_at=now() where test_code='standing_five_bound';

update public.control_test_definitions set version=2, protocol=jsonb_build_object(
  'start_method','砲丸投ピット／サークルから投てき方向を向いて実施。','attempts','最大2本。','rest','要設定。各測定間で疲労が結果へ大きく影響しないよう十分な休息を取る。','measurement_method','投てき距離と使用した砲丸重量を記録する。','foul_conditions','サークル／投てきエリアの規定位置を越えた場合。','adopted_record','ベスト記録。','equipment','砲丸（男子4kg・女子3kg。JUNIORは要設定）','notes','より詳細なフォーム規定は要設定。'
), updated_at=now() where test_code='shot_front_throw';

update public.control_test_definitions set version=2, protocol=jsonb_build_object(
  'start_method','砲丸投ピット／サークルから投てき方向に背を向けて実施。','attempts','最大2本。','rest','要設定。各測定間で疲労が結果へ大きく影響しないよう十分な休息を取る。','measurement_method','投てき距離と使用した砲丸重量を記録する。','foul_conditions','サークル／投てきエリアの規定位置を越えた場合。','adopted_record','ベスト記録。','equipment','砲丸（男子4kg・女子3kg。JUNIORは要設定）','notes','より詳細なフォーム規定は要設定。'
), updated_at=now() where test_code='shot_back_throw';

update public.control_test_definitions set version=2, ability_name_ja='反発パフォーマンス', ability_name_en='REACTIVE PERFORMANCE', description='短い接地で地面からの反発を利用し、腕振りを含めて素早く大きな跳躍につなげる能力を見る。', protocol=jsonb_build_object(
  'start_method','腕振り自由。','attempts','連続5回。','rest','要設定。各測定間で疲労が結果へ大きく影響しないよう十分な休息を取る。','measurement_method','5回すべての跳躍高・接地時間・RJ-indexを保存する。','foul_conditions','再試技条件を含め要設定。','adopted_record','5回の中で最も高いRJ-indexを代表値として採用。','equipment','ジャンプマット','notes','腕振りを使用するため、純粋な下肢Reactive Strengthのみを測るとは断定しない。'
), updated_at=now() where test_code='rebound_jump';

update public.control_test_definitions set version=2, category='SPEED ENDURANCE', description='高い走速度をできるだけ維持し、速度低下を抑える能力を見る。', protocol=jsonb_build_object(
  'start_method','全力で実施。','attempts','1本のみ。','rest','この種目をCONTROL TESTの最後に実施する。','measurement_method','YOUTH／ELITEは300m、JUNIOR／MASTERSは150mのタイムを測定する。','foul_conditions','要設定','adopted_record','1本の測定タイム。','equipment','タイム測定器具','notes','必ず全測定の最後に実施する。'
), updated_at=now() where test_code='speed_endurance_300m';

update public.control_test_class_settings set alternate_test_name='150m走', alternate_distance_m=150, updated_at=now()
where test_code='speed_endurance_300m' and program_class in ('ジュニア','マスターズ');
update public.control_test_class_settings set alternate_test_name='300m走', alternate_distance_m=300, updated_at=now()
where test_code='speed_endurance_300m' and program_class in ('ユース','エリート');
update public.control_test_class_settings set implement_weight_kg=case when gender='male' then 4 when gender='female' then 3 end, updated_at=now()
where test_code in ('shot_front_throw','shot_back_throw') and program_class <> 'ジュニア' and gender in ('male','female');

create table if not exists public.control_test_rj_trials (
  id bigint generated by default as identity primary key,
  measurement_id bigint not null references public.control_test_measurements(id) on delete cascade,
  scan_id uuid not null references public.control_test_scans(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  trial_number smallint not null check (trial_number between 1 and 5),
  jump_height_cm numeric not null check (jump_height_cm > 0),
  contact_time_ms numeric not null check (contact_time_ms > 0),
  rj_index numeric not null check (rj_index > 0),
  created_at timestamptz not null default now(),
  unique (measurement_id, trial_number)
);
create index if not exists control_test_rj_trials_scan_idx on public.control_test_rj_trials(scan_id, trial_number);
alter table public.control_test_rj_trials enable row level security;
drop policy if exists "Athletes and assigned coaches can read RJ trials" on public.control_test_rj_trials;
create policy "Athletes and assigned coaches can read RJ trials" on public.control_test_rj_trials for select to authenticated using (user_id=auth.uid() or public.is_assigned_coach(user_id));
drop policy if exists "Athletes can create RJ trials" on public.control_test_rj_trials;
create policy "Athletes can create RJ trials" on public.control_test_rj_trials for insert to authenticated with check (user_id=auth.uid() and exists(select 1 from public.control_test_measurements m where m.id=measurement_id and m.user_id=auth.uid()));
drop policy if exists "Athletes can update RJ trials" on public.control_test_rj_trials;
create policy "Athletes can update RJ trials" on public.control_test_rj_trials for update to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());
drop policy if exists "Athletes can delete RJ trials" on public.control_test_rj_trials;
create policy "Athletes can delete RJ trials" on public.control_test_rj_trials for delete to authenticated using (user_id=auth.uid());

-- Ranking direction remains lower-is-better for all timed categories.
create or replace function public.get_performance_rankings(p_category text, p_record_kind text, p_year integer default null)
returns table(overall_rank integer, overall_total integer, overall_top_percent numeric, class_rank integer, class_total integer, class_top_percent numeric, program_class text, gender text)
language sql security definer set search_path=public stable as $$
with caller as (select p.program_class,p.gender from public.players p where p.user_id=auth.uid() and p.member_status='active' limit 1),
personal_bests as (
 select r.user_id,p.program_class,p.gender,case when p_category in ('30m走','Flying 30m','50m走','150m走','300m走','100m','200m','400m','800m','1500m','5000m','100mH','110mH','400mH') then min(r.value) else max(r.value) end best_value
 from public.performance_records r join public.players p on p.user_id=r.user_id cross join caller c
 where r.category=p_category and r.record_kind=p_record_kind and (p_year is null or extract(year from r.date)::integer=p_year) and c.gender is not null and p.gender=c.gender and p.member_status='active'
 group by r.user_id,p.program_class,p.gender),
ranked as (
 select user_id,program_class,gender,
 rank() over(order by case when p_category in ('30m走','Flying 30m','50m走','150m走','300m走','100m','200m','400m','800m','1500m','5000m','100mH','110mH','400mH') then best_value end asc nulls last,case when p_category not in ('30m走','Flying 30m','50m走','150m走','300m走','100m','200m','400m','800m','1500m','5000m','100mH','110mH','400mH') then best_value end desc nulls last)::integer overall_position,
 count(*) over()::integer overall_count,
 case when program_class is not null then rank() over(partition by program_class order by case when p_category in ('30m走','Flying 30m','50m走','150m走','300m走','100m','200m','400m','800m','1500m','5000m','100mH','110mH','400mH') then best_value end asc nulls last,case when p_category not in ('30m走','Flying 30m','50m走','150m走','300m走','100m','200m','400m','800m','1500m','5000m','100mH','110mH','400mH') then best_value end desc nulls last)::integer end class_position,
 case when program_class is not null then count(*) over(partition by program_class)::integer end class_count from personal_bests)
select overall_position,overall_count,round(overall_position::numeric/overall_count*100,1),class_position,class_count,case when class_count>0 then round(class_position::numeric/class_count*100,1) end,ranked.program_class,ranked.gender from ranked where user_id=auth.uid(); $$;

create or replace function public.get_performance_leaderboard(p_category text,p_record_kind text,p_year integer default null)
returns table(ranking_scope text,leaderboard_position integer,display_name text,best_value numeric,is_current_user boolean)
language sql security definer set search_path=public stable as $$
with caller as (select program_class,gender from public.players where user_id=auth.uid() and member_status='active' limit 1),
personal_bests as (
 select r.user_id,p.name,p.program_class,p.ranking_name_public,case when p_category in ('30m走','Flying 30m','50m走','150m走','300m走','100m','200m','400m','800m','1500m','5000m','100mH','110mH','400mH') then min(r.value) else max(r.value) end best_value
 from public.performance_records r join public.players p on p.user_id=r.user_id cross join caller c where r.category=p_category and r.record_kind=p_record_kind and (p_year is null or extract(year from r.date)::integer=p_year) and c.gender is not null and p.gender=c.gender and p.member_status='active' group by r.user_id,p.name,p.program_class,p.ranking_name_public),
overall_ranked as (select *,rank() over(order by case when p_category in ('30m走','Flying 30m','50m走','150m走','300m走','100m','200m','400m','800m','1500m','5000m','100mH','110mH','400mH') then best_value end asc nulls last,case when p_category not in ('30m走','Flying 30m','50m走','150m走','300m走','100m','200m','400m','800m','1500m','5000m','100mH','110mH','400mH') then best_value end desc nulls last)::integer ranking_position from personal_bests),
class_ranked as (select pb.*,rank() over(order by case when p_category in ('30m走','Flying 30m','50m走','150m走','300m走','100m','200m','400m','800m','1500m','5000m','100mH','110mH','400mH') then best_value end asc nulls last,case when p_category not in ('30m走','Flying 30m','50m走','150m走','300m走','100m','200m','400m','800m','1500m','5000m','100mH','110mH','400mH') then best_value end desc nulls last)::integer ranking_position from personal_bests pb cross join caller c where c.program_class is not null and pb.program_class=c.program_class)
select 'overall',ranking_position,case when ranking_name_public or user_id=auth.uid() then name else coalesce(program_class,'VAULTEX')||'会員' end,best_value,user_id=auth.uid() from overall_ranked where ranking_position<=3
union all select 'class',ranking_position,case when ranking_name_public or user_id=auth.uid() then name else coalesce(program_class,'VAULTEX')||'会員' end,best_value,user_id=auth.uid() from class_ranked where ranking_position<=3 order by 1,2; $$;

revoke all on function public.get_performance_rankings(text,text,integer) from public;
grant execute on function public.get_performance_rankings(text,text,integer) to authenticated;
revoke all on function public.get_performance_leaderboard(text,text,integer) from public;
grant execute on function public.get_performance_leaderboard(text,text,integer) to authenticated;
