create table if not exists public.daily_checkins (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  checkin_date date not null,
  condition_score smallint not null check (condition_score between 1 and 5),
  fatigue_score smallint not null check (fatigue_score between 1 and 5),
  mood_score smallint not null check (mood_score between 1 and 5),
  note text null check (char_length(note) <= 200),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, checkin_date)
);

alter table public.daily_checkins enable row level security;

create index if not exists daily_checkins_user_date_idx
  on public.daily_checkins (user_id, checkin_date desc);

drop policy if exists "daily_checkins_select_own" on public.daily_checkins;
create policy "daily_checkins_select_own"
  on public.daily_checkins for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "daily_checkins_insert_own" on public.daily_checkins;
create policy "daily_checkins_insert_own"
  on public.daily_checkins for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists "daily_checkins_update_own" on public.daily_checkins;
create policy "daily_checkins_update_own"
  on public.daily_checkins for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

grant select, insert, update on table public.daily_checkins to authenticated;
grant usage, select on sequence public.daily_checkins_id_seq to authenticated;
