create table if not exists public.schedule_templates (
  id bigint generated by default as identity primary key,
  author_id uuid not null references auth.users(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 100),
  title text not null check (char_length(title) between 1 and 100),
  details text check (details is null or char_length(details) <= 2000),
  location text check (location is null or char_length(location) <= 200),
  schedule_type text not null default 'practice' check (schedule_type in ('practice', 'competition', 'measurement', 'other')),
  audience text not null check (audience in ('all', 'class')),
  program_class text check (program_class in ('ジュニア', 'ユース', 'エリート', 'マスターズ')),
  weekday smallint not null check (weekday between 0 and 6),
  start_time time not null,
  duration_minutes integer check (duration_minutes is null or duration_minutes between 0 and 1440),
  repeat_type text not null default 'weekly' check (repeat_type in ('once', 'weekly')),
  repeat_weeks integer not null default 8 check (repeat_weeks between 1 and 104),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check ((audience = 'all' and program_class is null) or (audience = 'class' and program_class is not null))
);

alter table public.schedule_templates enable row level security;

create policy "Coaches can read own schedule templates" on public.schedule_templates for select to authenticated
using (author_id = auth.uid());

create policy "Coaches can create own schedule templates" on public.schedule_templates for insert to authenticated
with check (author_id = auth.uid() and exists (select 1 from public.user_roles r where r.user_id = auth.uid() and r.role in ('coach', 'admin')));

create policy "Coaches can update own schedule templates" on public.schedule_templates for update to authenticated
using (author_id = auth.uid()) with check (author_id = auth.uid());

create policy "Coaches can delete own schedule templates" on public.schedule_templates for delete to authenticated
using (author_id = auth.uid());

create unique index if not exists schedule_templates_author_name_idx on public.schedule_templates(author_id, name);
