create table if not exists public.schedules (
  id bigint generated by default as identity primary key,
  author_id uuid not null references auth.users(id) on delete cascade,
  title text not null check (char_length(title) between 1 and 100),
  details text check (details is null or char_length(details) <= 2000),
  location text check (location is null or char_length(location) <= 200),
  starts_at timestamptz not null,
  ends_at timestamptz,
  schedule_type text not null default 'practice' check (schedule_type in ('practice', 'competition', 'measurement', 'other')),
  audience text not null check (audience in ('all', 'class')),
  program_class text check (program_class in ('ジュニア', 'ユース', 'エリート', 'マスターズ')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (ends_at is null or ends_at >= starts_at),
  check ((audience = 'all' and program_class is null) or (audience = 'class' and program_class is not null))
);

alter table public.schedules enable row level security;

create policy "Members can read relevant schedules" on public.schedules for select to authenticated
using (audience = 'all' or exists (select 1 from public.players p where p.user_id = auth.uid() and p.program_class = schedules.program_class));

create policy "Coaches can create schedules" on public.schedules for insert to authenticated
with check (author_id = auth.uid() and exists (select 1 from public.user_roles r where r.user_id = auth.uid() and r.role in ('coach', 'admin')));

create policy "Authors can update schedules" on public.schedules for update to authenticated
using (author_id = auth.uid()) with check (author_id = auth.uid());

create policy "Authors can delete schedules" on public.schedules for delete to authenticated
using (author_id = auth.uid());

create index if not exists schedules_starts_at_idx on public.schedules(starts_at);
