create table if not exists public.performance_goals (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  category text not null,
  target_value numeric not null check (target_value > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, category)
);

alter table public.performance_goals enable row level security;

create policy "Users can read their own performance goals"
on public.performance_goals for select using (auth.uid() = user_id);

create policy "Users can insert their own performance goals"
on public.performance_goals for insert with check (auth.uid() = user_id);

create policy "Users can update their own performance goals"
on public.performance_goals for update using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can delete their own performance goals"
on public.performance_goals for delete using (auth.uid() = user_id);

