create table if not exists public.feedback_requests (
  id bigint generated by default as identity primary key,
  record_id bigint not null references public.performance_records(id) on delete cascade,
  request_type text not null check (request_type in ('video', 'movement', 'awareness', 'improvement', 'other')),
  message text check (message is null or char_length(message) <= 500),
  priority text not null default 'normal' check (priority in ('normal', 'urgent')),
  status text not null default 'pending' check (status in ('pending', 'answered', 'cancelled')),
  answered_feedback_id bigint references public.coach_feedback(id) on delete set null,
  created_at timestamptz not null default now(),
  answered_at timestamptz
);

create unique index if not exists feedback_requests_one_pending_per_record on public.feedback_requests(record_id) where status = 'pending';
alter table public.feedback_requests enable row level security;

create policy "Athletes can read own feedback requests" on public.feedback_requests for select to authenticated
using (exists (select 1 from public.performance_records r where r.id = record_id and r.user_id = auth.uid()));
create policy "Assigned coaches can read feedback requests" on public.feedback_requests for select to authenticated
using (exists (select 1 from public.performance_records r where r.id = record_id and public.is_assigned_coach(r.user_id)));
create policy "Athletes can create feedback requests" on public.feedback_requests for insert to authenticated
with check (status = 'pending' and exists (select 1 from public.performance_records r where r.id = record_id and r.user_id = auth.uid()));
create policy "Athletes can cancel feedback requests" on public.feedback_requests for update to authenticated
using (status = 'pending' and exists (select 1 from public.performance_records r where r.id = record_id and r.user_id = auth.uid()))
with check (status = 'cancelled' and exists (select 1 from public.performance_records r where r.id = record_id and r.user_id = auth.uid()));

create or replace function public.limit_pending_feedback_requests()
returns trigger language plpgsql security definer set search_path = public as $$
declare athlete_id uuid;
begin
  select user_id into athlete_id from public.performance_records where id = new.record_id;
  if (select count(*) from public.feedback_requests fr join public.performance_records r on r.id = fr.record_id where r.user_id = athlete_id and fr.status = 'pending') >= 2 then
    raise exception '未回答のフィードバック依頼は1人2件までです';
  end if;
  return new;
end; $$;
drop trigger if exists limit_pending_feedback_requests_trigger on public.feedback_requests;
create trigger limit_pending_feedback_requests_trigger before insert on public.feedback_requests for each row execute function public.limit_pending_feedback_requests();

create or replace function public.complete_feedback_request()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  update public.feedback_requests set status = 'answered', answered_feedback_id = new.id, answered_at = now()
  where record_id = new.record_id and status = 'pending';
  return new;
end; $$;
drop trigger if exists complete_feedback_request_trigger on public.coach_feedback;
create trigger complete_feedback_request_trigger after insert on public.coach_feedback for each row execute function public.complete_feedback_request();
