alter table public.push_subscriptions
  add column if not exists notify_attendance_reminder boolean not null default true;

create table if not exists public.family_attendance_reminders (
  id bigint generated by default as identity primary key,
  guardian_id uuid not null references auth.users(id) on delete cascade,
  athlete_id uuid not null references auth.users(id) on delete cascade,
  schedule_id bigint not null references public.schedules(id) on delete cascade,
  sent_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (guardian_id, athlete_id, schedule_id)
);

alter table public.family_attendance_reminders enable row level security;
revoke all on table public.family_attendance_reminders from anon, authenticated;
revoke all on sequence public.family_attendance_reminders_id_seq from anon, authenticated;

drop function if exists public.get_push_targets(text, bigint, text, text);
create function public.get_push_targets(p_kind text, p_record_id bigint default null, p_audience text default null, p_program_class text default null)
returns table(endpoint text, p256dh text, auth text, portal text)
language sql
security definer
set search_path = ''
stable
as $$
  with caller_authorized as (
    select exists (
      select 1 from public.user_roles r
      where r.user_id = auth.uid() and r.role in ('coach', 'admin')
    ) as allowed
  )
  select distinct target.endpoint, target.p256dh, target.auth, target.portal
  from (
    select s.endpoint, s.p256dh, s.auth, 'athlete'::text as portal
    from public.push_subscriptions s
    join public.players p on p.user_id = s.user_id
    where p.member_status = 'active'
      and (
        (p_kind = 'feedback' and s.notify_feedback and exists (
          select 1 from public.performance_records pr where pr.id = p_record_id and pr.user_id = s.user_id
        ))
        or (p_kind = 'announcement' and s.notify_important and (p_audience = 'all' or (p_audience = 'class' and p.program_class = p_program_class)))
        or (p_kind = 'schedule' and s.notify_schedule and (p_audience = 'all' or (p_audience = 'class' and p.program_class = p_program_class)))
      )
    union all
    select s.endpoint, s.p256dh, s.auth, 'family'::text as portal
    from public.push_subscriptions s
    join public.guardian_athlete_links link on link.guardian_id = s.user_id and link.status = 'active'
    join public.players p on p.user_id = link.athlete_id and p.member_status = 'active'
    where p_kind in ('announcement', 'schedule')
      and ((p_kind = 'announcement' and s.notify_important) or (p_kind = 'schedule' and s.notify_schedule))
      and (p_audience = 'all' or (p_audience = 'class' and p.program_class = p_program_class))
  ) target
  cross join caller_authorized caller
  where caller.allowed;
$$;

revoke all on function public.get_push_targets(text, bigint, text, text) from public, anon;
grant execute on function public.get_push_targets(text, bigint, text, text) to authenticated;

comment on table public.family_attendance_reminders is
  'Delivery claims for one-time FAMILY attendance reminder push notifications.';
