create table if not exists public.ai_companion_conversations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null default '新しい相談' check (char_length(title) between 1 and 80),
  status text not null default 'active' check (status in ('active', 'archived')),
  last_message_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ai_companion_messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references public.ai_companion_conversations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('user', 'companion')),
  content text not null check (char_length(content) between 1 and 2000),
  response_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists ai_companion_conversations_user_recent_idx
  on public.ai_companion_conversations (user_id, last_message_at desc);
create index if not exists ai_companion_messages_conversation_idx
  on public.ai_companion_messages (conversation_id, created_at, id);
create index if not exists ai_companion_messages_user_idx
  on public.ai_companion_messages (user_id, created_at desc);

alter table public.ai_companion_conversations enable row level security;
alter table public.ai_companion_messages enable row level security;

drop policy if exists "Athletes manage own AI conversations" on public.ai_companion_conversations;
create policy "Athletes manage own AI conversations"
on public.ai_companion_conversations for all to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Athletes read own AI messages" on public.ai_companion_messages;
create policy "Athletes read own AI messages"
on public.ai_companion_messages for select to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Athletes add own AI messages" on public.ai_companion_messages;
create policy "Athletes add own AI messages"
on public.ai_companion_messages for insert to authenticated
with check (
  (select auth.uid()) = user_id
  and exists (
    select 1 from public.ai_companion_conversations conversation
    where conversation.id = conversation_id
      and conversation.user_id = (select auth.uid())
  )
);

grant select, insert, update, delete on public.ai_companion_conversations to authenticated;
grant select, insert on public.ai_companion_messages to authenticated;
grant usage, select on sequence public.ai_companion_messages_id_seq to authenticated;

comment on table public.ai_companion_conversations is
  'User-owned VAULTEX AI Navigator & Companion conversation history.';
comment on column public.ai_companion_messages.response_payload is
  'Versioned navigation actions and safety metadata returned with a companion response.';
