alter table public.push_subscriptions
  add column if not exists notify_training_log_reminder boolean not null default true;

create table if not exists public.training_log_reminders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  reminder_date date not null,
  sent_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (user_id, reminder_date)
);

alter table public.training_log_reminders enable row level security;

create index if not exists training_log_reminders_user_date_idx
  on public.training_log_reminders (user_id, reminder_date desc);

revoke all on table public.training_log_reminders from anon, authenticated;
revoke all on sequence public.training_log_reminders_id_seq from anon, authenticated;

