alter table public.schedules
  add column if not exists registration_enabled boolean not null default false,
  add column if not exists registration_opens_at timestamptz,
  add column if not exists registration_deadline timestamptz;

alter table public.schedules
  drop constraint if exists schedules_registration_period_check;
alter table public.schedules
  add constraint schedules_registration_period_check check (
    registration_deadline is null
    or registration_opens_at is null
    or registration_deadline >= registration_opens_at
  );

create table if not exists public.competition_applications (
  id bigint generated by default as identity primary key,
  schedule_id bigint not null references public.schedules(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  events text not null check (char_length(events) between 1 and 500),
  note text check (note is null or char_length(note) <= 500),
  status text not null default 'submitted' check (status in ('submitted', 'withdrawn')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (schedule_id, user_id)
);

alter table public.competition_applications enable row level security;

create policy "Members read own competition applications"
on public.competition_applications for select to authenticated
using (
  user_id = (select auth.uid())
  or exists (
    select 1 from public.schedules s
    where s.id = schedule_id and s.author_id = (select auth.uid())
  )
);

create policy "Members submit competition applications"
on public.competition_applications for insert to authenticated
with check (
  user_id = (select auth.uid())
  and status = 'submitted'
  and exists (
    select 1 from public.schedules s
    where s.id = schedule_id
      and s.schedule_type = 'competition'
      and s.registration_enabled
      and (s.registration_opens_at is null or now() >= s.registration_opens_at)
      and (s.registration_deadline is null or now() <= s.registration_deadline)
      and (
        s.audience = 'all'
        or exists (
          select 1 from public.players p
          where p.user_id = (select auth.uid()) and p.program_class = s.program_class
        )
      )
  )
);

create policy "Members update own competition applications"
on public.competition_applications for update to authenticated
using (user_id = (select auth.uid()))
with check (
  user_id = (select auth.uid())
  and (
    status = 'withdrawn'
    or exists (
      select 1 from public.schedules s
      where s.id = schedule_id
        and s.schedule_type = 'competition'
        and s.registration_enabled
        and (s.registration_opens_at is null or now() >= s.registration_opens_at)
        and (s.registration_deadline is null or now() <= s.registration_deadline)
    )
  )
);

create index if not exists competition_applications_schedule_status_idx
  on public.competition_applications(schedule_id, status);
create index if not exists competition_applications_user_idx
  on public.competition_applications(user_id);

grant select, insert, update on public.competition_applications to authenticated;
grant usage, select on sequence public.competition_applications_id_seq to authenticated;
