alter table public.schedules
  add column if not exists is_personal_slot boolean not null default false,
  add column if not exists personal_booked boolean not null default false;

alter table public.schedules drop constraint if exists schedules_schedule_type_check;
alter table public.schedules add constraint schedules_schedule_type_check check (schedule_type in ('practice', 'competition', 'measurement', 'other', 'personal'));
alter table public.schedule_templates drop constraint if exists schedule_templates_schedule_type_check;
alter table public.schedule_templates add constraint schedule_templates_schedule_type_check check (schedule_type in ('practice', 'competition', 'measurement', 'other', 'personal'));

create table if not exists public.personal_session_bookings (
  id bigint generated by default as identity primary key,
  schedule_id bigint not null unique references public.schedules(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  note text check (note is null or char_length(note) <= 500),
  created_at timestamptz not null default now()
);

alter table public.personal_session_bookings enable row level security;

create policy "Members read own personal bookings"
on public.personal_session_bookings for select to authenticated
using ((select auth.uid()) = user_id or exists (
  select 1 from public.schedules s where s.id = schedule_id and s.author_id = (select auth.uid())
));

create policy "Members book available personal slots"
on public.personal_session_bookings for insert to authenticated
with check ((select auth.uid()) = user_id and exists (
  select 1 from public.schedules s
  where s.id = schedule_id and s.is_personal_slot and not s.personal_booked and s.starts_at > now()
));

create policy "Members cancel own personal bookings"
on public.personal_session_bookings for delete to authenticated
using ((select auth.uid()) = user_id);

create index if not exists personal_session_bookings_user_idx on public.personal_session_bookings(user_id);
grant select, insert, delete on public.personal_session_bookings to authenticated;
grant usage, select on sequence public.personal_session_bookings_id_seq to authenticated;

create schema if not exists private;
create or replace function private.sync_personal_slot_booking()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if tg_op = 'INSERT' then
    update public.schedules
    set personal_booked = true, updated_at = now()
    where id = new.schedule_id and is_personal_slot and not personal_booked and starts_at > now();
    if not found then raise exception 'この枠はすでに予約済み、または受付を終了しています。'; end if;
    insert into public.schedule_attendance(schedule_id, user_id, status, comment, updated_at)
    values (new.schedule_id, new.user_id, 'attending', new.note, now())
    on conflict (schedule_id, user_id) do update set status = 'attending', comment = excluded.comment, updated_at = now();
    return new;
  end if;
  delete from public.schedule_attendance where schedule_id = old.schedule_id and user_id = old.user_id;
  update public.schedules set personal_booked = false, updated_at = now() where id = old.schedule_id;
  return old;
end;
$$;

revoke all on function private.sync_personal_slot_booking() from public, anon, authenticated;
drop trigger if exists sync_personal_slot_booking_insert on public.personal_session_bookings;
create trigger sync_personal_slot_booking_insert before insert on public.personal_session_bookings
for each row execute function private.sync_personal_slot_booking();
drop trigger if exists sync_personal_slot_booking_delete on public.personal_session_bookings;
create trigger sync_personal_slot_booking_delete after delete on public.personal_session_bookings
for each row execute function private.sync_personal_slot_booking();
