-- VAULTEX CONTROL TEST Ver.2 / CONTACT PROFILE Ver.1 BETA.
-- Historical scans remain untouched: version columns are intentionally nullable.

alter table public.control_test_scans
  add column if not exists control_test_version text,
  add column if not exists protocol_version integer,
  add column if not exists contact_profile_version text,
  add column if not exists contact_profile_code text,
  add column if not exists contact_profile_snapshot jsonb;

alter table public.control_test_scans
  drop constraint if exists control_test_scans_contact_profile_code_check,
  add constraint control_test_scans_contact_profile_code_check
    check (contact_profile_code is null or contact_profile_code in ('QUICK','BALANCED','FORCE','NOT_MEASURED'));

comment on column public.control_test_scans.control_test_version is 'CONTROL TEST version used when the scan was measured. NULL means legacy.';
comment on column public.control_test_scans.contact_profile_snapshot is 'Immutable CONTACT PROFILE result and thresholds used for this scan.';

create table if not exists public.contact_profile_settings (
  version text primary key,
  quick_upper_ms integer not null check (quick_upper_ms > 0),
  balanced_upper_ms integer not null check (balanced_upper_ms > quick_upper_ms),
  junior_drop_height_cm numeric not null check (junior_drop_height_cm > 0),
  youth_drop_height_cm numeric not null check (youth_drop_height_cm > 0),
  elite_drop_height_cm numeric not null check (elite_drop_height_cm > 0),
  masters_drop_height_cm numeric not null check (masters_drop_height_cm > 0),
  status text not null default 'beta' check (status in ('draft','beta','active','retired')),
  is_current boolean not null default false,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists contact_profile_one_current_idx on public.contact_profile_settings(is_current) where is_current;
alter table public.contact_profile_settings enable row level security;
drop policy if exists "Authenticated users read contact profile settings" on public.contact_profile_settings;
create policy "Authenticated users read contact profile settings" on public.contact_profile_settings for select to authenticated using (true);
drop policy if exists "Admins manage contact profile settings" on public.contact_profile_settings;
create policy "Admins manage contact profile settings" on public.contact_profile_settings for all to authenticated
using (exists(select 1 from public.user_roles r where r.user_id=(select auth.uid()) and r.role='admin'))
with check (exists(select 1 from public.user_roles r where r.user_id=(select auth.uid()) and r.role='admin'));

insert into public.contact_profile_settings
  (version,quick_upper_ms,balanced_upper_ms,junior_drop_height_cm,youth_drop_height_cm,elite_drop_height_cm,masters_drop_height_cm,status,is_current,notes)
values ('contact-v1-beta',188,222,20,30,30,30,'beta',true,'DJ代表試技の接地時間を整数msで判定。境界値は188msと222ms。')
on conflict (version) do nothing;

create table if not exists public.control_test_jump_trials (
  id bigint generated by default as identity primary key,
  measurement_id bigint not null references public.control_test_measurements(id) on delete cascade,
  scan_id uuid not null references public.control_test_scans(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  test_code text not null check (test_code in ('vertical_jump','drop_jump')),
  trial_number smallint not null check (trial_number between 1 and 3),
  drop_height_cm numeric check (drop_height_cm is null or drop_height_cm > 0),
  jump_height_cm numeric not null check (jump_height_cm > 0),
  contact_time_ms numeric check (contact_time_ms is null or contact_time_ms > 0),
  rsi numeric check (rsi is null or rsi > 0),
  is_valid boolean not null default true,
  invalid_reason text,
  equipment text,
  protocol_version integer not null default 2,
  measured_at timestamptz not null default now(),
  raw_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique(measurement_id,trial_number)
);
create index if not exists control_test_jump_trials_scan_test_idx on public.control_test_jump_trials(scan_id,test_code,trial_number);
alter table public.control_test_jump_trials enable row level security;
drop policy if exists "Athletes and assigned coaches read jump trials" on public.control_test_jump_trials;
create policy "Athletes and assigned coaches read jump trials" on public.control_test_jump_trials for select to authenticated
using (user_id=(select auth.uid()) or public.is_assigned_coach(user_id));
drop policy if exists "Athletes create jump trials" on public.control_test_jump_trials;
create policy "Athletes create jump trials" on public.control_test_jump_trials for insert to authenticated
with check (user_id=(select auth.uid()) and exists(select 1 from public.control_test_measurements m where m.id=measurement_id and m.scan_id=scan_id and m.user_id=(select auth.uid())));
drop policy if exists "Athletes update jump trials" on public.control_test_jump_trials;
create policy "Athletes update jump trials" on public.control_test_jump_trials for update to authenticated
using (user_id=(select auth.uid())) with check (user_id=(select auth.uid()));
drop policy if exists "Athletes delete jump trials" on public.control_test_jump_trials;
create policy "Athletes delete jump trials" on public.control_test_jump_trials for delete to authenticated using (user_id=(select auth.uid()));

alter table public.control_test_rj_trials
  add column if not exists protocol_version integer,
  add column if not exists is_valid boolean not null default true,
  add column if not exists invalid_reason text,
  add column if not exists equipment text,
  add column if not exists measured_at timestamptz,
  add column if not exists raw_data jsonb not null default '{}'::jsonb;

update public.control_test_definitions set
  version=4, category='CMJ', ability_name_ja='垂直跳躍パフォーマンス', ability_name_en='COUNTERMOVEMENT JUMP',
  description='腕振りを使わず、下肢の反動動作から上方向へ発揮した跳躍高を確認する。', primary_metric_key='jump_height_cm', primary_unit='cm',
  protocol=jsonb_build_object('start_method','両手を腰に置き、両足で静止してから反動動作を用いて跳ぶ。腕振りなし。','attempts','最大3本。','rest','要設定。','measurement_method','ジャンプマットで各試技の跳躍高を測定する。','foul_conditions','腕が腰から離れた場合など測定条件を満たさない試技。','adopted_record','有効試技の最大跳躍高。','equipment','S-CADE等のジャンプマット','notes','VAULTEX SCOREの6能力には含めない。'), updated_at=now()
where test_code='vertical_jump';

update public.control_test_definitions set
  version=4, category='ドロップジャンプ', ability_name_ja='接地反発パフォーマンス', ability_name_en='DROP JUMP',
  description='一定の台高から自然に落下し、短い接地から跳躍へつなげるパフォーマンスを確認する。', primary_metric_key='rsi', primary_unit='RSI',
  protocol=jsonb_build_object('start_method','両手を腰に置き、台から自然に前へ落下する。腕振りなし・両足接地。','attempts','最大3本。','rest','要設定。','measurement_method','JUNIORは20cm、YOUTH／ELITE／MASTERSは30cmを標準とし、跳躍高・接地時間・RSIを保存する。','foul_conditions','台から跳び上がる、腕が腰から離れる、片足接地、バランスを崩す等。','adopted_record','有効試技で最も高いRSI。CONTACT PROFILEはその試技の接地時間を使用。','equipment','台・S-CADE等のジャンプマット','notes','VAULTEX SCOREの6能力には含めない。'), updated_at=now()
where test_code='drop_jump';

update public.control_test_definitions set version=4,
  description='腕振りを使わず、短い接地から連続して跳躍へつなげる反発パフォーマンスを確認する。',
  protocol=jsonb_build_object('start_method','両手を腰に置き、両足で連続跳躍する。腕振りなし。','attempts','設定された3〜5回の連続跳躍。','rest','要設定。','measurement_method','各跳躍の跳躍高・接地時間・RJ-indexを保存する。','foul_conditions','手が腰から離れる、動作停止、マットから外れる等。','adopted_record','有効試技の最大RJ-index。','equipment','S-CADE等のジャンプマット','notes','旧Protocol v1（腕振り自由）は履歴上区別する。') ,updated_at=now()
where test_code='rebound_jump';

update public.control_test_class_settings set protocol_overrides=coalesce(protocol_overrides,'{}'::jsonb)||jsonb_build_object('drop_height_cm',case when program_class='ジュニア' then 20 else 30 end), updated_at=now()
where test_code='drop_jump';
