create table if not exists public.personal_calendar_input_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null check (char_length(title) between 1 and 120),
  entry_date date not null,
  all_day boolean not null default true,
  start_time time without time zone,
  end_time time without time zone,
  entry_type text not null default 'personal_training',
  location text,
  journal text,
  awareness_categories text[] not null default '{}',
  record_kind text not null default 'unofficial-athletics',
  record_category text,
  record_value numeric,
  wind_speed numeric,
  record_unit text,
  color text not null default 'sky',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists personal_calendar_input_history_user_updated_idx
  on public.personal_calendar_input_history (user_id, updated_at desc);

alter table public.personal_calendar_input_history enable row level security;

drop policy if exists "Users can read own calendar input history" on public.personal_calendar_input_history;
create policy "Users can read own calendar input history"
  on public.personal_calendar_input_history for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "Users can create own calendar input history" on public.personal_calendar_input_history;
create policy "Users can create own calendar input history"
  on public.personal_calendar_input_history for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users can update own calendar input history" on public.personal_calendar_input_history;
create policy "Users can update own calendar input history"
  on public.personal_calendar_input_history for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users can delete own calendar input history" on public.personal_calendar_input_history;
create policy "Users can delete own calendar input history"
  on public.personal_calendar_input_history for delete
  to authenticated
  using ((select auth.uid()) = user_id);

grant select, insert, update, delete on public.personal_calendar_input_history to authenticated;

