create table public.line_account_connections (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  line_user_id text not null,
  portal text not null check (portal in ('athlete', 'family')),
  display_name text,
  notify_important boolean not null default true,
  notify_schedule boolean not null default true,
  notify_feedback boolean not null default true,
  notify_training_log_reminder boolean not null default true,
  notify_attendance_reminder boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, portal),
  unique (line_user_id)
);

alter table public.line_account_connections enable row level security;

create policy "Users read own LINE connection"
on public.line_account_connections for select to authenticated
using ((select auth.uid()) = user_id);

create policy "Users update own LINE preferences"
on public.line_account_connections for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Users disconnect own LINE account"
on public.line_account_connections for delete to authenticated
using ((select auth.uid()) = user_id);

revoke all on table public.line_account_connections from anon;
grant select, update, delete on table public.line_account_connections to authenticated;

create index line_account_connections_user_id_idx
on public.line_account_connections (user_id);
