create table if not exists public.user_roles (
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('athlete', 'coach', 'admin')),
  created_at timestamptz not null default now(),
  primary key (user_id, role)
);

create table if not exists public.coach_class_assignments (
  coach_id uuid not null references auth.users(id) on delete cascade,
  program_class text not null check (program_class in ('ジュニア', 'ユース', 'エリート', 'マスターズ')),
  created_at timestamptz not null default now(),
  primary key (coach_id, program_class)
);

create table if not exists public.coach_feedback (
  id bigint generated by default as identity primary key,
  record_id bigint not null references public.performance_records(id) on delete cascade,
  coach_id uuid not null references auth.users(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 1000),
  created_at timestamptz not null default now()
);

alter table public.user_roles enable row level security;
alter table public.coach_class_assignments enable row level security;
alter table public.coach_feedback enable row level security;

create or replace function public.is_assigned_coach(p_athlete_id uuid)
returns boolean language sql security definer stable set search_path = public as $$
  select exists (
    select 1 from public.user_roles ur
    join public.coach_class_assignments cca on cca.coach_id = ur.user_id
    join public.players p on p.user_id = p_athlete_id and p.program_class = cca.program_class
    where ur.user_id = auth.uid() and ur.role = 'coach'
  );
$$;

revoke all on function public.is_assigned_coach(uuid) from public;
grant execute on function public.is_assigned_coach(uuid) to authenticated;

drop policy if exists "Users can read their own roles" on public.user_roles;
create policy "Users can read their own roles" on public.user_roles for select to authenticated using (user_id = auth.uid());
drop policy if exists "Coaches can read their assignments" on public.coach_class_assignments;
create policy "Coaches can read their assignments" on public.coach_class_assignments for select to authenticated using (coach_id = auth.uid());

drop policy if exists "Assigned coaches can read performance records" on public.performance_records;
create policy "Assigned coaches can read performance records" on public.performance_records for select to authenticated using (public.is_assigned_coach(user_id));

drop policy if exists "Assigned coaches can read athlete videos" on storage.objects;
create policy "Assigned coaches can read athlete videos" on storage.objects for select to authenticated
using (bucket_id = 'performance-videos' and public.is_assigned_coach(((storage.foldername(name))[1])::uuid));

drop policy if exists "Athletes and assigned coaches can read feedback" on public.coach_feedback;
create policy "Athletes and assigned coaches can read feedback" on public.coach_feedback for select to authenticated
using (coach_id = auth.uid() or exists (select 1 from public.performance_records r where r.id = record_id and (r.user_id = auth.uid() or public.is_assigned_coach(r.user_id))));

drop policy if exists "Assigned coaches can create feedback" on public.coach_feedback;
create policy "Assigned coaches can create feedback" on public.coach_feedback for insert to authenticated
with check (coach_id = auth.uid() and exists (select 1 from public.performance_records r where r.id = record_id and public.is_assigned_coach(r.user_id)));

drop policy if exists "Coaches can update their feedback" on public.coach_feedback;
create policy "Coaches can update their feedback" on public.coach_feedback for update to authenticated using (coach_id = auth.uid()) with check (coach_id = auth.uid());
drop policy if exists "Coaches can delete their feedback" on public.coach_feedback;
create policy "Coaches can delete their feedback" on public.coach_feedback for delete to authenticated using (coach_id = auth.uid());

insert into public.user_roles (user_id, role)
select user_id, 'coach' from public.players where name = '宮内勝史'
on conflict do nothing;

insert into public.coach_class_assignments (coach_id, program_class)
select p.user_id, c.program_class
from public.players p
cross join (values ('ジュニア'), ('ユース'), ('エリート'), ('マスターズ')) as c(program_class)
where p.name = '宮内勝史'
on conflict do nothing;
