alter table public.players
  add column if not exists birth_date date,
  add column if not exists height_cm numeric,
  add column if not exists weight_kg numeric;

alter table public.players
  drop constraint if exists players_height_cm_check,
  add constraint players_height_cm_check check (height_cm is null or height_cm between 50 and 260),
  drop constraint if exists players_weight_kg_check,
  add constraint players_weight_kg_check check (weight_kg is null or weight_kg between 10 and 400);

create table if not exists public.control_test_definitions (
  test_code text primary key,
  version integer not null default 1 check (version > 0),
  category text not null,
  sort_order integer not null,
  ability_name_ja text not null,
  ability_name_en text not null,
  description text not null,
  primary_metric_key text not null,
  primary_unit text not null,
  better_direction text not null check (better_direction in ('higher', 'lower')),
  protocol jsonb not null default '{}'::jsonb,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.control_test_class_settings (
  id bigint generated by default as identity primary key,
  test_code text not null references public.control_test_definitions(test_code) on delete cascade,
  program_class text not null check (program_class in ('ジュニア', 'ユース', 'エリート', 'マスターズ')),
  gender text check (gender is null or gender in ('male', 'female')),
  enabled boolean not null default true,
  alternate_test_name text,
  alternate_distance_m numeric check (alternate_distance_m is null or alternate_distance_m > 0),
  implement_weight_kg numeric check (implement_weight_kg is null or implement_weight_kg > 0),
  protocol_overrides jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);
create unique index if not exists control_test_class_settings_unique_idx
  on public.control_test_class_settings (test_code, program_class, coalesce(gender, 'all'));

create table if not exists public.control_test_scans (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  scan_number integer not null,
  measured_on date not null,
  version integer not null default 1,
  status text not null default 'complete' check (status in ('draft', 'complete')),
  profile_snapshot jsonb not null default '{}'::jsonb,
  notes text check (notes is null or char_length(notes) <= 1000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, scan_number)
);

create or replace function public.assign_control_test_scan_number()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.scan_number is null or new.scan_number < 1 then
    select coalesce(max(scan_number), 0) + 1 into new.scan_number
    from public.control_test_scans where user_id = new.user_id;
  end if;
  return new;
end;
$$;

drop trigger if exists assign_control_test_scan_number on public.control_test_scans;
create trigger assign_control_test_scan_number before insert on public.control_test_scans
for each row execute function public.assign_control_test_scan_number();

create table if not exists public.control_test_measurements (
  id bigint generated by default as identity primary key,
  scan_id uuid not null references public.control_test_scans(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  test_code text not null references public.control_test_definitions(test_code),
  performance_record_id bigint references public.performance_records(id) on delete set null,
  primary_value numeric not null check (primary_value > 0),
  metrics jsonb not null default '{}'::jsonb,
  implement_weight_kg numeric check (implement_weight_kg is null or implement_weight_kg > 0),
  equipment text,
  notes text check (notes is null or char_length(notes) <= 500),
  created_at timestamptz not null default now(),
  unique (scan_id, test_code)
);

create index if not exists control_test_scans_user_date_idx on public.control_test_scans(user_id, measured_on desc);
create index if not exists control_test_measurements_user_test_idx on public.control_test_measurements(user_id, test_code, created_at desc);
create index if not exists control_test_measurements_record_idx on public.control_test_measurements(performance_record_id);

alter table public.control_test_definitions enable row level security;
alter table public.control_test_class_settings enable row level security;
alter table public.control_test_scans enable row level security;
alter table public.control_test_measurements enable row level security;

drop policy if exists "Authenticated users can read control test definitions" on public.control_test_definitions;
create policy "Authenticated users can read control test definitions" on public.control_test_definitions for select to authenticated using (true);
drop policy if exists "Authenticated users can read control test settings" on public.control_test_class_settings;
create policy "Authenticated users can read control test settings" on public.control_test_class_settings for select to authenticated using (true);

drop policy if exists "Athletes and assigned coaches can read scans" on public.control_test_scans;
create policy "Athletes and assigned coaches can read scans" on public.control_test_scans for select to authenticated using (user_id = auth.uid() or public.is_assigned_coach(user_id));
drop policy if exists "Athletes can create scans" on public.control_test_scans;
create policy "Athletes can create scans" on public.control_test_scans for insert to authenticated with check (user_id = auth.uid());
drop policy if exists "Athletes can update scans" on public.control_test_scans;
create policy "Athletes can update scans" on public.control_test_scans for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
drop policy if exists "Athletes can delete scans" on public.control_test_scans;
create policy "Athletes can delete scans" on public.control_test_scans for delete to authenticated using (user_id = auth.uid());

drop policy if exists "Athletes and assigned coaches can read measurements" on public.control_test_measurements;
create policy "Athletes and assigned coaches can read measurements" on public.control_test_measurements for select to authenticated using (user_id = auth.uid() or public.is_assigned_coach(user_id));
drop policy if exists "Athletes can create measurements" on public.control_test_measurements;
create policy "Athletes can create measurements" on public.control_test_measurements for insert to authenticated with check (user_id = auth.uid() and exists (select 1 from public.control_test_scans s where s.id = scan_id and s.user_id = auth.uid()));
drop policy if exists "Athletes can update measurements" on public.control_test_measurements;
create policy "Athletes can update measurements" on public.control_test_measurements for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
drop policy if exists "Athletes can delete measurements" on public.control_test_measurements;
create policy "Athletes can delete measurements" on public.control_test_measurements for delete to authenticated using (user_id = auth.uid());

insert into public.control_test_definitions (test_code, category, sort_order, ability_name_ja, ability_name_en, description, primary_metric_key, primary_unit, better_direction, protocol)
values
('acceleration_30m','30m走',1,'加速力','ACCELERATION','短い距離で素早く速度を高める能力。','time_30m','秒','lower','{"start_method":"要設定","attempts":"要設定","rest":"要設定","measurement_method":"0–30mのタイムを測定。光電管導入後は0–10mも保存可能。","foul_conditions":"要設定","adopted_record":"要設定","equipment":"現段階：要設定／将来：光電管","notes":"要設定"}'),
('standing_long_jump','立幅跳',2,'水平瞬発力','HORIZONTAL EXPLOSIVE POWER','一度の動作で前方向へ大きな力を発揮する能力。','distance','m','higher','{"start_method":"要設定","attempts":"要設定","rest":"要設定","measurement_method":"要設定","foul_conditions":"要設定","adopted_record":"要設定","equipment":"要設定","notes":"要設定"}'),
('standing_five_bound','立五段跳',3,'連続水平跳躍力','BOUNCE POWER','前方向への大きな力発揮を連続してつなげる能力。','distance','m','higher','{"start_method":"要設定","attempts":"要設定","rest":"要設定","measurement_method":"要設定","foul_conditions":"要設定","adopted_record":"要設定","equipment":"要設定","notes":"要設定"}'),
('shot_front_throw','砲丸フロント投げ',4,'全身爆発力','TOTAL BODY POWER','下肢・体幹・上半身を連動させ、全身で大きな力を発揮する能力。','distance','m','higher','{"start_method":"要設定","attempts":"要設定","rest":"要設定","measurement_method":"使用重量と投距離を記録。","foul_conditions":"要設定","adopted_record":"要設定","equipment":"重量変更可能な砲丸","notes":"JUNIOR重量は要設定"}'),
('shot_back_throw','砲丸バック投げ',5,'全身爆発力','TOTAL BODY POWER','下肢・体幹・上半身を連動させ、全身で大きな力を発揮する能力。','distance','m','higher','{"start_method":"要設定","attempts":"要設定","rest":"要設定","measurement_method":"使用重量と投距離を記録。","foul_conditions":"要設定","adopted_record":"要設定","equipment":"重量変更可能な砲丸","notes":"JUNIOR重量は要設定"}'),
('rebound_jump','リバウンドジャンプ',6,'反発力','REACTIVE STRENGTH','短い接地時間で力を発揮し、素早く地面から跳ね返る能力。','rj_index','RJ-index','higher','{"start_method":"要設定","attempts":"要設定","rest":"要設定","measurement_method":"跳躍高・接地時間・RJ-indexを保存。","foul_conditions":"要設定","adopted_record":"要設定","equipment":"ジャンプマット（導入予定）","notes":"要設定"}'),
('speed_endurance_300m','300m走',7,'スピード持久力','SPEED ENDURANCE','高い走速度をできるだけ維持し、速度低下を抑える能力。','time','秒','lower','{"start_method":"要設定","attempts":"要設定","rest":"要設定","measurement_method":"300m走タイムを測定。","foul_conditions":"要設定","adopted_record":"要設定","equipment":"要設定","notes":"JUNIORは300mまたは代替距離を要設定"}')
on conflict (test_code) do update set category=excluded.category, sort_order=excluded.sort_order, ability_name_ja=excluded.ability_name_ja, ability_name_en=excluded.ability_name_en, description=excluded.description, primary_metric_key=excluded.primary_metric_key, primary_unit=excluded.primary_unit, better_direction=excluded.better_direction, protocol=excluded.protocol, updated_at=now();

insert into public.control_test_class_settings (test_code, program_class, gender, implement_weight_kg)
select d.test_code, c.program_class, g.gender,
  case when d.test_code in ('shot_front_throw','shot_back_throw') and c.program_class <> 'ジュニア' then case when g.gender='male' then 4 else 3 end else null end
from public.control_test_definitions d
cross join (values ('ジュニア'),('ユース'),('エリート'),('マスターズ')) c(program_class)
cross join (values ('male'),('female')) g(gender)
on conflict do nothing;
