create table if not exists public.video_feedback_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  video_path text not null,
  event_name text not null check (char_length(event_name) between 1 and 80),
  awareness_category text check (awareness_category is null or awareness_category in ('リズム', '力感', 'スタート', '動作', '気持ち', '感覚', 'その他')),
  message text check (message is null or char_length(message) <= 500),
  priority text not null default 'normal' check (priority in ('normal', 'urgent')),
  status text not null default 'pending' check (status in ('pending', 'answered', 'cancelled')),
  response text check (response is null or char_length(response) <= 1000),
  responded_by uuid references auth.users(id) on delete set null,
  responded_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.video_feedback_requests enable row level security;

create policy "Athletes read own video feedback requests" on public.video_feedback_requests
for select to authenticated using (user_id = auth.uid());
create policy "Athletes create own video feedback requests" on public.video_feedback_requests
for insert to authenticated with check (user_id = auth.uid() and status = 'pending' and response is null and responded_by is null);
create policy "Athletes delete own video feedback requests" on public.video_feedback_requests
for delete to authenticated using (user_id = auth.uid());

create policy "Assigned coaches read video feedback requests" on public.video_feedback_requests
for select to authenticated using (public.is_assigned_coach(user_id));

create policy "Assigned coaches answer video feedback requests" on public.video_feedback_requests
for update to authenticated using (public.is_assigned_coach(user_id))
with check (public.is_assigned_coach(user_id) and status = 'answered' and responded_by = auth.uid());

create or replace function public.limit_pending_video_feedback_requests()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if (select count(*) from public.video_feedback_requests where user_id = new.user_id and status = 'pending') >= 2 then
    raise exception '未回答の動画フィードバック依頼は1人2件までです';
  end if;
  return new;
end; $$;
drop trigger if exists limit_pending_video_feedback_requests_trigger on public.video_feedback_requests;
create trigger limit_pending_video_feedback_requests_trigger before insert on public.video_feedback_requests
for each row execute function public.limit_pending_video_feedback_requests();

create policy "Assigned coaches can read requested standalone videos"
on storage.objects for select to authenticated
using (
  bucket_id = 'performance-videos' and exists (
    select 1 from public.video_feedback_requests request
    where request.video_path = name and public.is_assigned_coach(request.user_id)
  )
);
