create schema if not exists private;

create table if not exists public.family_guardians (
  user_id uuid primary key references auth.users(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 100),
  email text not null,
  phone text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.guardian_athlete_links (
  guardian_id uuid not null references auth.users(id) on delete cascade,
  athlete_id uuid not null references auth.users(id) on delete cascade,
  relationship text not null default 'guardian' check (relationship in ('father', 'mother', 'guardian', 'other')),
  guardian_role text not null default 'family_member' check (guardian_role in ('primary_guardian', 'family_member')),
  status text not null default 'active' check (status in ('pending', 'active', 'revoked')),
  invited_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (guardian_id, athlete_id),
  check (guardian_id <> athlete_id)
);

create table if not exists public.family_invitations (
  id uuid primary key default gen_random_uuid(),
  athlete_id uuid not null references auth.users(id) on delete cascade,
  invited_by uuid not null references auth.users(id) on delete cascade,
  email text not null,
  guardian_name text not null check (char_length(guardian_name) between 1 and 100),
  phone text,
  relationship text not null default 'guardian' check (relationship in ('father', 'mother', 'guardian', 'other')),
  guardian_role text not null default 'family_member' check (guardian_role in ('primary_guardian', 'family_member')),
  token_hash text not null unique check (char_length(token_hash) = 64),
  expires_at timestamptz not null,
  accepted_by uuid references auth.users(id) on delete set null,
  accepted_at timestamptz,
  created_at timestamptz not null default now(),
  check (expires_at > created_at),
  check ((accepted_at is null and accepted_by is null) or (accepted_at is not null and accepted_by is not null))
);

create table if not exists public.family_monthly_reports (
  id bigint generated by default as identity primary key,
  athlete_id uuid not null references auth.users(id) on delete cascade,
  report_month date not null check (report_month = date_trunc('month', report_month)::date),
  coach_id uuid not null references auth.users(id) on delete cascade,
  coach_message text check (coach_message is null or char_length(coach_message) <= 1000),
  next_month text check (next_month is null or char_length(next_month) <= 500),
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (athlete_id, report_month)
);

create index if not exists guardian_athlete_links_guardian_idx on public.guardian_athlete_links (guardian_id) where status = 'active';
create index if not exists guardian_athlete_links_athlete_idx on public.guardian_athlete_links (athlete_id) where status = 'active';
create index if not exists family_invitations_email_idx on public.family_invitations (lower(email), expires_at desc);
create index if not exists family_reports_athlete_month_idx on public.family_monthly_reports (athlete_id, report_month desc);

alter table public.family_guardians enable row level security;
alter table public.guardian_athlete_links enable row level security;
alter table public.family_invitations enable row level security;
alter table public.family_monthly_reports enable row level security;

create or replace function private.is_active_guardian_of(p_athlete_id uuid, p_guardian_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select p_guardian_id is not null and exists (
    select 1 from public.guardian_athlete_links link
    where link.guardian_id = p_guardian_id
      and link.athlete_id = p_athlete_id
      and link.status = 'active'
  );
$$;

create or replace function private.is_primary_guardian_of(p_athlete_id uuid, p_guardian_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select p_guardian_id is not null and exists (
    select 1 from public.guardian_athlete_links link
    where link.guardian_id = p_guardian_id
      and link.athlete_id = p_athlete_id
      and link.status = 'active'
      and link.guardian_role = 'primary_guardian'
  );
$$;

revoke all on function private.is_active_guardian_of(uuid, uuid) from public, anon;
revoke all on function private.is_primary_guardian_of(uuid, uuid) from public, anon;
grant usage on schema private to authenticated;
grant execute on function private.is_active_guardian_of(uuid, uuid) to authenticated;
grant execute on function private.is_primary_guardian_of(uuid, uuid) to authenticated;

create policy "Guardians read own profile" on public.family_guardians for select to authenticated
using (user_id = (select auth.uid()));
create policy "Guardians update own profile" on public.family_guardians for update to authenticated
using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));

create policy "Guardians read own family links" on public.guardian_athlete_links for select to authenticated
using (guardian_id = (select auth.uid()));
create policy "Assigned coaches read athlete family links" on public.guardian_athlete_links for select to authenticated
using (public.is_assigned_coach(athlete_id));
create policy "Primary guardians add family links" on public.guardian_athlete_links for insert to authenticated
with check (private.is_primary_guardian_of(athlete_id) and guardian_role = 'family_member');
create policy "Primary guardians update family links" on public.guardian_athlete_links for update to authenticated
using (private.is_primary_guardian_of(athlete_id))
with check (private.is_primary_guardian_of(athlete_id));

create policy "Inviters and primary guardians read invitations" on public.family_invitations for select to authenticated
using (invited_by = (select auth.uid()) or private.is_primary_guardian_of(athlete_id));
create policy "Coaches and primary guardians create invitations" on public.family_invitations for insert to authenticated
with check (invited_by = (select auth.uid()) and (public.is_assigned_coach(athlete_id) or private.is_primary_guardian_of(athlete_id)));

create policy "Families read published monthly reports" on public.family_monthly_reports for select to authenticated
using (published and private.is_active_guardian_of(athlete_id));
create policy "Assigned coaches read monthly reports" on public.family_monthly_reports for select to authenticated
using (public.is_assigned_coach(athlete_id));
create policy "Assigned coaches create monthly reports" on public.family_monthly_reports for insert to authenticated
with check (coach_id = (select auth.uid()) and public.is_assigned_coach(athlete_id));
create policy "Assigned coaches update monthly reports" on public.family_monthly_reports for update to authenticated
using (coach_id = (select auth.uid()) and public.is_assigned_coach(athlete_id))
with check (coach_id = (select auth.uid()) and public.is_assigned_coach(athlete_id));

grant select, update on public.family_guardians to authenticated;
grant select, insert, update on public.guardian_athlete_links to authenticated;
grant select, insert on public.family_invitations to authenticated;
grant select, insert, update on public.family_monthly_reports to authenticated;
grant usage, select on sequence public.family_monthly_reports_id_seq to authenticated;

alter table public.user_roles drop constraint if exists user_roles_role_check;
alter table public.user_roles add constraint user_roles_role_check check (role in ('athlete', 'coach', 'admin', 'guardian'));

create or replace function public.accept_family_invitation(p_token text)
returns table(athlete_id uuid, guardian_role text)
language plpgsql
security definer
set search_path = ''
as $$
declare
  invitation public.family_invitations%rowtype;
  current_user_id uuid := auth.uid();
  current_email text := lower(coalesce(auth.jwt() ->> 'email', ''));
begin
  if current_user_id is null then raise exception 'Authentication required'; end if;
  if p_token is null or char_length(p_token) < 32 then raise exception 'Invalid invitation'; end if;

  select * into invitation
  from public.family_invitations i
  where i.token_hash = encode(extensions.digest(p_token, 'sha256'), 'hex')
  for update;

  if invitation.id is null or invitation.accepted_at is not null or invitation.expires_at <= now() then
    raise exception 'Invitation is invalid or expired';
  end if;
  if lower(invitation.email) <> current_email then raise exception 'Invitation email does not match'; end if;

  insert into public.family_guardians (user_id, name, email, phone)
  values (current_user_id, invitation.guardian_name, invitation.email, invitation.phone)
  on conflict (user_id) do update set
    name = excluded.name, email = excluded.email,
    phone = coalesce(excluded.phone, public.family_guardians.phone), updated_at = now();

  insert into public.guardian_athlete_links (guardian_id, athlete_id, relationship, guardian_role, status, invited_by)
  values (current_user_id, invitation.athlete_id, invitation.relationship, invitation.guardian_role, 'active', invitation.invited_by)
  on conflict (guardian_id, athlete_id) do update set
    relationship = excluded.relationship, guardian_role = excluded.guardian_role,
    status = 'active', invited_by = excluded.invited_by, updated_at = now();

  insert into public.user_roles (user_id, role) values (current_user_id, 'guardian') on conflict do nothing;
  update public.family_invitations set accepted_by = current_user_id, accepted_at = now() where id = invitation.id;
  return query select invitation.athlete_id, invitation.guardian_role;
end;
$$;

revoke all on function public.accept_family_invitation(text) from public, anon;
grant execute on function public.accept_family_invitation(text) to authenticated;

comment on table public.guardian_athlete_links is 'Many-to-many FAMILY account links. Athletes may exist without an athlete login; athlete_id is the durable profile owner UUID.';
comment on table public.family_monthly_reports is 'Only parent-facing coach messages. Athlete private notes and consultation content must never be copied here.';
