alter table public.ai_companion_conversations
  add column if not exists event_name text,
  add column if not exists resolution_status text not null default 'organizing'
    check (resolution_status in ('organizing', 'handed_off', 'resolved')),
  add column if not exists coach_handoff_at timestamptz;

create table if not exists public.ai_coach_consultations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  conversation_id uuid not null unique references public.ai_companion_conversations(id) on delete cascade,
  event_name text,
  consultation_summary text not null,
  current_feeling text,
  tried_actions text,
  data_summary text,
  requested_focus text,
  attachment_candidates jsonb not null default '[]'::jsonb,
  related_record_id bigint references public.performance_records(id) on delete set null,
  assigned_coach_id uuid references auth.users(id) on delete set null,
  status text not null default 'pending' check (status in ('pending', 'active', 'resolved')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  resolved_at timestamptz
);

create table if not exists public.ai_coach_consultation_messages (
  id bigint generated by default as identity primary key,
  consultation_id uuid not null references public.ai_coach_consultations(id) on delete cascade,
  sender_id uuid not null references auth.users(id) on delete cascade,
  sender_role text not null check (sender_role in ('athlete', 'coach')),
  body text not null check (char_length(body) between 1 and 2000),
  created_at timestamptz not null default now()
);

create index if not exists ai_coach_consultations_user_recent_idx on public.ai_coach_consultations(user_id, created_at desc);
create index if not exists ai_coach_consultations_coach_status_idx on public.ai_coach_consultations(assigned_coach_id, status, created_at desc);
create index if not exists ai_coach_consultation_messages_thread_idx on public.ai_coach_consultation_messages(consultation_id, created_at, id);

alter table public.ai_coach_consultations enable row level security;
alter table public.ai_coach_consultation_messages enable row level security;

drop policy if exists "Athletes read own AI coach consultations" on public.ai_coach_consultations;
create policy "Athletes read own AI coach consultations" on public.ai_coach_consultations for select to authenticated using (user_id = auth.uid());
drop policy if exists "Athletes create own AI coach consultations" on public.ai_coach_consultations;
create policy "Athletes create own AI coach consultations" on public.ai_coach_consultations for insert to authenticated with check (user_id = auth.uid() and assigned_coach_id is null);
drop policy if exists "Athletes update own AI coach consultations" on public.ai_coach_consultations;
create policy "Athletes update own AI coach consultations" on public.ai_coach_consultations for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
drop policy if exists "Assigned coaches read AI coach consultations" on public.ai_coach_consultations;
create policy "Assigned coaches read AI coach consultations" on public.ai_coach_consultations for select to authenticated using (public.is_assigned_coach(user_id));
drop policy if exists "Assigned coaches update AI coach consultations" on public.ai_coach_consultations;
create policy "Assigned coaches update AI coach consultations" on public.ai_coach_consultations for update to authenticated using (public.is_assigned_coach(user_id)) with check (public.is_assigned_coach(user_id));

drop policy if exists "Participants read AI coach messages" on public.ai_coach_consultation_messages;
create policy "Participants read AI coach messages" on public.ai_coach_consultation_messages for select to authenticated using (exists (select 1 from public.ai_coach_consultations c where c.id = consultation_id and (c.user_id = auth.uid() or public.is_assigned_coach(c.user_id))));
drop policy if exists "Participants add AI coach messages" on public.ai_coach_consultation_messages;
create policy "Participants add AI coach messages" on public.ai_coach_consultation_messages for insert to authenticated with check (sender_id = auth.uid() and exists (select 1 from public.ai_coach_consultations c where c.id = consultation_id and ((sender_role = 'athlete' and c.user_id = auth.uid()) or (sender_role = 'coach' and public.is_assigned_coach(c.user_id)))));

grant select, insert, update on public.ai_coach_consultations to authenticated;
grant select, insert on public.ai_coach_consultation_messages to authenticated;
grant usage, select on sequence public.ai_coach_consultation_messages_id_seq to authenticated;

comment on table public.ai_coach_consultations is 'AIで整理した後に選手と担当コーチが直接やり取りする相談。';
