create table if not exists public.scan_teams (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 1 and 100),
  organization_type text not null default 'school_club' check (organization_type in ('school_club','sports_club','other')),
  created_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.scan_team_members (
  team_id uuid not null references public.scan_teams(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'coach' check (role in ('owner','coach','viewer')),
  created_at timestamptz not null default now(),
  primary key (team_id,user_id)
);

create table if not exists public.scan_team_athletes (
  id uuid primary key default gen_random_uuid(),
  team_id uuid not null references public.scan_teams(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 100),
  student_number text,
  grade text,
  gender text check (gender is null or gender in ('male','female','other')),
  event text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.scan_team_sessions (
  id uuid primary key default gen_random_uuid(),
  team_id uuid not null references public.scan_teams(id) on delete cascade,
  measured_on date not null,
  title text not null default 'CONTROL TEST',
  status text not null default 'draft' check (status in ('draft','complete')),
  created_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.scan_team_measurements (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.scan_team_sessions(id) on delete cascade,
  team_id uuid not null references public.scan_teams(id) on delete cascade,
  athlete_id uuid not null references public.scan_team_athletes(id) on delete cascade,
  test_code text not null references public.control_test_definitions(test_code),
  primary_value numeric not null check (primary_value > 0),
  attempts jsonb not null default '[]'::jsonb,
  entered_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (session_id,athlete_id,test_code)
);

create index if not exists scan_team_athletes_team_idx on public.scan_team_athletes(team_id,active,name);
create index if not exists scan_team_sessions_team_date_idx on public.scan_team_sessions(team_id,measured_on desc);
create index if not exists scan_team_measurements_athlete_idx on public.scan_team_measurements(athlete_id,test_code,created_at desc);

alter table public.scan_teams enable row level security;
alter table public.scan_team_members enable row level security;
alter table public.scan_team_athletes enable row level security;
alter table public.scan_team_sessions enable row level security;
alter table public.scan_team_measurements enable row level security;

revoke all on public.scan_teams, public.scan_team_members, public.scan_team_athletes, public.scan_team_sessions, public.scan_team_measurements from anon;
grant select,insert,update,delete on public.scan_teams, public.scan_team_members, public.scan_team_athletes, public.scan_team_sessions, public.scan_team_measurements to authenticated;
grant usage,select on all sequences in schema public to authenticated;

create policy "Team members read teams" on public.scan_teams for select to authenticated
using (exists(select 1 from public.scan_team_members m where m.team_id=id and m.user_id=(select auth.uid())));
create policy "Users read own team memberships" on public.scan_team_members for select to authenticated
using (user_id=(select auth.uid()));
create policy "Team members read athletes" on public.scan_team_athletes for select to authenticated
using (exists(select 1 from public.scan_team_members m where m.team_id=scan_team_athletes.team_id and m.user_id=(select auth.uid())));
create policy "Team members read sessions" on public.scan_team_sessions for select to authenticated
using (exists(select 1 from public.scan_team_members m where m.team_id=scan_team_sessions.team_id and m.user_id=(select auth.uid())));
create policy "Team members read measurements" on public.scan_team_measurements for select to authenticated
using (exists(select 1 from public.scan_team_members m where m.team_id=scan_team_measurements.team_id and m.user_id=(select auth.uid())));

comment on table public.scan_teams is 'Standalone VAULTEX SCAN organizations such as school athletics clubs.';
comment on table public.scan_team_athletes is 'Team-only athlete roster; no email address or auth account is required.';
