create table if not exists public.schedule_periods (
  id bigint generated by default as identity primary key,
  author_id uuid not null references auth.users(id) on delete cascade,
  label text check (label is null or char_length(label) <= 100),
  phase text not null check (phase in ('build', 'recovery', 'taper', 'competition')),
  starts_on date not null,
  ends_on date not null,
  audience text not null check (audience in ('all', 'class')),
  program_class text check (program_class in ('ジュニア', 'ユース', 'エリート', 'マスターズ')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (ends_on >= starts_on),
  check ((audience = 'all' and program_class is null) or (audience = 'class' and program_class is not null))
);

alter table public.schedule_periods enable row level security;

create policy "Members can read relevant schedule periods"
on public.schedule_periods for select to authenticated
using (
  author_id = (select auth.uid())
  or audience = 'all'
  or exists (
    select 1 from public.players p
    where p.user_id = (select auth.uid())
      and p.program_class = schedule_periods.program_class
  )
);

create policy "Coaches can create schedule periods"
on public.schedule_periods for insert to authenticated
with check (
  author_id = (select auth.uid())
  and exists (
    select 1 from public.user_roles r
    where r.user_id = (select auth.uid()) and r.role in ('coach', 'admin')
  )
);

create policy "Authors can update schedule periods"
on public.schedule_periods for update to authenticated
using (author_id = (select auth.uid()))
with check (author_id = (select auth.uid()));

create policy "Authors can delete schedule periods"
on public.schedule_periods for delete to authenticated
using (author_id = (select auth.uid()));

grant select, insert, update, delete on public.schedule_periods to authenticated;
grant usage, select on sequence public.schedule_periods_id_seq to authenticated;

create index if not exists schedule_periods_dates_idx
on public.schedule_periods (starts_on, ends_on);

comment on table public.schedule_periods is
  'Date-only training periods used to color schedule calendar ranges independently from schedule events.';
