create table if not exists public.personal_calendar_goals (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null check (char_length(title) between 1 and 120),
  target_date date not null,
  event_name text,
  target_value numeric,
  target_unit text,
  status text not null default 'active' check (status in ('active', 'completed', 'archived')),
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists personal_calendar_goals_one_active_per_user
  on public.personal_calendar_goals (user_id)
  where status = 'active';

create index if not exists personal_calendar_goals_user_date_idx
  on public.personal_calendar_goals (user_id, target_date desc);

alter table public.personal_calendar_goals enable row level security;

create policy "Members and assigned coaches read calendar goals"
on public.personal_calendar_goals for select to authenticated
using ((select auth.uid()) = user_id or public.is_assigned_coach(user_id));

create policy "Members insert own calendar goal"
on public.personal_calendar_goals for insert to authenticated
with check ((select auth.uid()) = user_id);

create policy "Members update own calendar goal"
on public.personal_calendar_goals for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Members delete own calendar goal"
on public.personal_calendar_goals for delete to authenticated
using ((select auth.uid()) = user_id);

grant select, insert, update, delete on public.personal_calendar_goals to authenticated;
grant usage, select on sequence public.personal_calendar_goals_id_seq to authenticated;
