create table if not exists public.athlete_scan_standard_history (
  id bigint generated by default as identity primary key,
  from_version text not null,
  to_version text not null references public.athlete_scan_standard_sets(version) on delete restrict,
  change_kind text not null check (change_kind in ('standard','type_settings')),
  standard_id bigint,
  gender text check (gender is null or gender in ('male','female')),
  test_code text,
  field_name text not null,
  old_value jsonb,
  new_value jsonb,
  reason text not null check (char_length(reason) between 3 and 1000),
  changed_by uuid not null references auth.users(id) on delete restrict,
  changed_at timestamptz not null default now()
);

create index if not exists athlete_scan_standard_history_changed_at_idx
  on public.athlete_scan_standard_history (changed_at desc);
create index if not exists athlete_scan_standard_history_version_idx
  on public.athlete_scan_standard_history (to_version);

alter table public.athlete_scan_standard_history enable row level security;

drop policy if exists "Admins read standard history" on public.athlete_scan_standard_history;
create policy "Admins read standard history" on public.athlete_scan_standard_history
for select to authenticated using (
  exists (select 1 from public.user_roles r where r.user_id = (select auth.uid()) and r.role = 'admin')
);

drop policy if exists "Admins manage standard sets" on public.athlete_scan_standard_sets;
create policy "Admins manage standard sets" on public.athlete_scan_standard_sets
for all to authenticated
using (exists (select 1 from public.user_roles r where r.user_id = (select auth.uid()) and r.role = 'admin'))
with check (exists (select 1 from public.user_roles r where r.user_id = (select auth.uid()) and r.role = 'admin'));

drop policy if exists "Admins manage athlete standards" on public.athlete_scan_standards;
create policy "Admins manage athlete standards" on public.athlete_scan_standards
for all to authenticated
using (exists (select 1 from public.user_roles r where r.user_id = (select auth.uid()) and r.role = 'admin'))
with check (exists (select 1 from public.user_roles r where r.user_id = (select auth.uid()) and r.role = 'admin'));

drop policy if exists "Admins manage athlete type settings" on public.athlete_scan_type_settings;
create policy "Admins manage athlete type settings" on public.athlete_scan_type_settings
for all to authenticated
using (exists (select 1 from public.user_roles r where r.user_id = (select auth.uid()) and r.role = 'admin'))
with check (exists (select 1 from public.user_roles r where r.user_id = (select auth.uid()) and r.role = 'admin'));

comment on table public.athlete_scan_standard_history is
  'Immutable audit trail for versioned VAULTEX STANDARD and ATHLETE TYPE setting changes.';
