create table if not exists public.athlete_scan_standard_sets (
  version text primary key,
  label text not null,
  status text not null default 'beta' check (status in ('draft','beta','active','retired')),
  is_current boolean not null default false,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists athlete_scan_one_current_standard_idx
  on public.athlete_scan_standard_sets (is_current) where is_current;

create table if not exists public.athlete_scan_standards (
  id bigint generated by default as identity primary key,
  standard_version text not null references public.athlete_scan_standard_sets(version) on delete cascade,
  gender text not null check (gender in ('male','female')),
  test_code text not null references public.control_test_definitions(test_code),
  equipment text,
  weight_kg numeric,
  distance_m numeric,
  jump_count smallint,
  score_100_value numeric,
  score_0_value numeric,
  higher_is_better boolean not null,
  status text not null default 'active' check (status in ('active','pending','retired')),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (weight_kg is null or weight_kg > 0),
  check (distance_m is null or distance_m > 0),
  check (jump_count is null or jump_count > 0),
  check (score_100_value is null or score_100_value >= 0),
  check (score_0_value is null or score_0_value >= 0)
);

create unique index if not exists athlete_scan_standards_condition_idx on public.athlete_scan_standards (
  standard_version, gender, test_code,
  coalesce(equipment, ''), coalesce(weight_kg, -1), coalesce(distance_m, -1), coalesce(jump_count, -1)
);
create index if not exists athlete_scan_standards_lookup_idx
  on public.athlete_scan_standards (standard_version, gender, test_code, status);

create table if not exists public.athlete_scan_type_settings (
  standard_version text primary key references public.athlete_scan_standard_sets(version) on delete cascade,
  balanced_max_spread numeric not null check (balanced_max_spread >= 0),
  composite_max_gap numeric not null check (composite_max_gap >= 0),
  type_descriptions jsonb not null default '{}'::jsonb,
  notes text,
  updated_at timestamptz not null default now()
);

alter table public.control_test_scans
  add column if not exists athlete_standard_version text references public.athlete_scan_standard_sets(version),
  add column if not exists athlete_evaluated_at timestamptz;

alter table public.athlete_scan_standard_sets enable row level security;
alter table public.athlete_scan_standards enable row level security;
alter table public.athlete_scan_type_settings enable row level security;

drop policy if exists "Authenticated users can read athlete standard sets" on public.athlete_scan_standard_sets;
create policy "Authenticated users can read athlete standard sets" on public.athlete_scan_standard_sets for select to authenticated using (true);
drop policy if exists "Authenticated users can read athlete standards" on public.athlete_scan_standards;
create policy "Authenticated users can read athlete standards" on public.athlete_scan_standards for select to authenticated using (true);
drop policy if exists "Authenticated users can read athlete type settings" on public.athlete_scan_type_settings;
create policy "Authenticated users can read athlete type settings" on public.athlete_scan_type_settings for select to authenticated using (true);

insert into public.athlete_scan_standard_sets (version, label, status, is_current, notes)
values ('v1-beta', 'VAULTEX STANDARD Ver.1 / BETA', 'beta', true, '全年代共通の絶対スケール。年齢補正は行わない。')
on conflict (version) do update set label=excluded.label, status=excluded.status, is_current=excluded.is_current, notes=excluded.notes, updated_at=now();

insert into public.athlete_scan_standards
  (standard_version, gender, test_code, equipment, weight_kg, distance_m, jump_count, score_100_value, score_0_value, higher_is_better, status, notes)
values
  ('v1-beta','male','acceleration_30m','光電管',null,30,null,2.50,5.00,false,'active','Flying 30m（30〜60m計測区間）'),
  ('v1-beta','female','acceleration_30m','光電管',null,30,null,2.85,5.70,false,'active','Flying 30m（30〜60m計測区間）'),
  ('v1-beta','male','standing_long_jump',null,null,null,null,3.50,0,true,'active',null),
  ('v1-beta','female','standing_long_jump',null,null,null,null,3.00,0,true,'active',null),
  ('v1-beta','male','standing_five_bound',null,null,null,3,10.00,0,true,'active','立三段跳'),
  ('v1-beta','female','standing_five_bound',null,null,null,3,9.00,0,true,'active','立三段跳'),
  ('v1-beta','male','standing_five_bound',null,null,null,5,17.50,0,true,'active','立五段跳'),
  ('v1-beta','female','standing_five_bound',null,null,null,5,16.00,0,true,'active','立五段跳'),
  ('v1-beta','male','shot_front_throw','砲丸',4,null,null,20.00,0,true,'active',null),
  ('v1-beta','female','shot_front_throw','砲丸',3,null,null,18.00,0,true,'active',null),
  ('v1-beta','male','shot_back_throw','砲丸',4,null,null,23.00,0,true,'active',null),
  ('v1-beta','female','shot_back_throw','砲丸',3,null,null,20.00,0,true,'active',null),
  ('v1-beta','male','shot_front_throw','2kgメディシンボール',2,null,null,null,null,true,'pending','VAULTEX STANDARD設定中'),
  ('v1-beta','female','shot_front_throw','2kgメディシンボール',2,null,null,null,null,true,'pending','VAULTEX STANDARD設定中'),
  ('v1-beta','male','shot_back_throw','2kgメディシンボール',2,null,null,null,null,true,'pending','VAULTEX STANDARD設定中'),
  ('v1-beta','female','shot_back_throw','2kgメディシンボール',2,null,null,null,null,true,'pending','VAULTEX STANDARD設定中'),
  ('v1-beta','male','rebound_jump','S-CADE等のジャンプマット',null,null,null,5.00,0,true,'active',null),
  ('v1-beta','female','rebound_jump','S-CADE等のジャンプマット',null,null,null,4.50,0,true,'active',null),
  ('v1-beta','male','speed_endurance_300m',null,null,150,null,14.00,28.00,false,'active',null),
  ('v1-beta','female','speed_endurance_300m',null,null,150,null,16.00,32.00,false,'active',null),
  ('v1-beta','male','speed_endurance_300m',null,null,300,null,32.00,64.00,false,'active',null),
  ('v1-beta','female','speed_endurance_300m',null,null,300,null,35.00,70.00,false,'active',null)
on conflict (standard_version, gender, test_code, coalesce(equipment, ''), coalesce(weight_kg, -1), coalesce(distance_m, -1), coalesce(jump_count, -1))
do update set score_100_value=excluded.score_100_value, score_0_value=excluded.score_0_value,
  higher_is_better=excluded.higher_is_better, status=excluded.status, notes=excluded.notes, updated_at=now();

insert into public.athlete_scan_type_settings
  (standard_version, balanced_max_spread, composite_max_gap, type_descriptions, notes)
values ('v1-beta', 5, 8, '{
  "SPEED":"高い速度を発揮し、その速度を維持する特性が現在の身体能力構成に強く表れています。",
  "POWER":"一度の動作で大きな力を発揮し、全身へ伝える特性が現在の身体能力構成に強く表れています。",
  "REACTIVE":"地面から受けた力を、素早く次の動作や連続した出力へつなげる特性が現在の身体能力構成に強く表れています。",
  "BALANCED":"速度・出力・反発の3特性が、現在の身体能力構成にバランスよく表れています。",
  "SPEED × POWER":"速度を発揮・維持する特性と、大きな力を全身へ伝える特性が現在の身体能力構成に表れています。",
  "SPEED × REACTIVE":"速度を発揮・維持する特性と、地面からの力を素早く次の動作へつなげる特性が現在の身体能力構成に表れています。",
  "POWER × SPEED":"大きな力を全身へ伝える特性と、速度を発揮・維持する特性が現在の身体能力構成に表れています。",
  "POWER × REACTIVE":"大きな力を全身へ伝える特性と、地面からの力を素早く次の動作へつなげる特性が現在の身体能力構成に表れています。",
  "REACTIVE × SPEED":"地面からの力を素早く次の動作へつなげる特性と、速度を発揮・維持する特性が現在の身体能力構成に表れています。",
  "REACTIVE × POWER":"地面からの力を素早く次の動作へつなげる特性と、大きな力を全身へ伝える特性が現在の身体能力構成に表れています。"
}'::jsonb, '暫定値。3軸最大差5点以内をBALANCED、上位2軸差8点以内を複合TYPEとする。')
on conflict (standard_version) do update set balanced_max_spread=excluded.balanced_max_spread,
  composite_max_gap=excluded.composite_max_gap, type_descriptions=excluded.type_descriptions,
  notes=excluded.notes, updated_at=now();

update public.control_test_scans
set athlete_standard_version='v1-beta', athlete_evaluated_at=coalesce(athlete_evaluated_at, now())
where athlete_standard_version is null;

comment on table public.athlete_scan_standards is 'Versioned VAULTEX SCORE standards. NULL values mean evaluation pending.';
comment on column public.control_test_scans.athlete_standard_version is 'STANDARD version used to evaluate this SCAN.';
