create table if not exists public.announcements (
  id bigint generated by default as identity primary key,
  author_id uuid not null references auth.users(id) on delete cascade,
  title text not null check (char_length(title) between 1 and 100),
  body text not null check (char_length(body) between 1 and 2000),
  audience text not null check (audience in ('all', 'class')),
  program_class text check (program_class in ('ジュニア', 'ユース', 'エリート', 'マスターズ')),
  priority text not null default 'normal' check (priority in ('normal', 'important')),
  created_at timestamptz not null default now(),
  check ((audience = 'all' and program_class is null) or (audience = 'class' and program_class is not null))
);

create table if not exists public.announcement_reads (
  announcement_id bigint not null references public.announcements(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  read_at timestamptz not null default now(),
  primary key (announcement_id, user_id)
);

alter table public.announcements enable row level security;
alter table public.announcement_reads enable row level security;

drop policy if exists "Members can read relevant announcements" on public.announcements;
create policy "Members can read relevant announcements" on public.announcements for select to authenticated
using (audience = 'all' or exists (select 1 from public.players p where p.user_id = auth.uid() and p.program_class = announcements.program_class));

drop policy if exists "Coaches can create announcements" on public.announcements;
create policy "Coaches can create announcements" on public.announcements for insert to authenticated
with check (author_id = auth.uid() and exists (select 1 from public.user_roles r where r.user_id = auth.uid() and r.role in ('coach', 'admin')));

drop policy if exists "Authors can update announcements" on public.announcements;
create policy "Authors can update announcements" on public.announcements for update to authenticated using (author_id = auth.uid()) with check (author_id = auth.uid());
drop policy if exists "Authors can delete announcements" on public.announcements;
create policy "Authors can delete announcements" on public.announcements for delete to authenticated using (author_id = auth.uid());

drop policy if exists "Users can read their announcement status" on public.announcement_reads;
create policy "Users can read their announcement status" on public.announcement_reads for select to authenticated using (user_id = auth.uid());
drop policy if exists "Users can mark announcements read" on public.announcement_reads;
create policy "Users can mark announcements read" on public.announcement_reads for insert to authenticated with check (user_id = auth.uid());
