"use client";
import Image from "next/image";
import { useEffect, useState } from "react";
import { CheckSquare2, Copy, LoaderCircle, QrCode, Square } from "lucide-react";
import { controlTestDefinitions } from "@/lib/control-test";

type Participant={athlete_id:string;status:string;last_saved_at:string;submitted_at:string|null;scan_team_athletes:{name:string}|null};
export default function HostSessionClient({teamId}:{teamId:string}){const [date,setDate]=useState(()=>new Date().toLocaleDateString("en-CA",{timeZone:"Asia/Tokyo"}));const [codes,setCodes]=useState(controlTestDefinitions.map(item=>item.code));const [creating,setCreating]=useState(false);const [session,setSession]=useState<{id:string;joinUrl:string;qrDataUrl:string}|null>(null);const [participants,setParticipants]=useState<Participant[]>([]);const [message,setMessage]=useState("");
 useEffect(()=>{if(!session)return;let active=true;const load=async()=>{try{const response=await fetch(`/api/scan/teams/${teamId}/self-session?sessionId=${session.id}`,{cache:"no-store"});const result=await response.json();if(active&&response.ok)setParticipants(result.participants??[]);}catch{}};void load();const timer=setInterval(load,3000);return()=>{active=false;clearInterval(timer)}},[session,teamId]);
 function toggle(code:string){setCodes(current=>current.includes(code)?current.filter(item=>item!==code):[...current,code])}
 async function create(){if(!codes.length){setMessage("種目を1つ以上選択してください。");return}setCreating(true);setMessage("");try{const response=await fetch(`/api/scan/teams/${teamId}/self-session`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({date,testCodes:codes})});const result=await response.json();if(!response.ok)throw new Error(result.error);setSession({id:result.sessionId,joinUrl:result.joinUrl,qrDataUrl:result.qrDataUrl});}catch(error){setMessage(error instanceof Error?error.message:"作成できませんでした。")}finally{setCreating(false)}}
 if(session)return <div className="mt-8 grid gap-6 lg:grid-cols-[390px_1fr]"><section className="rounded-3xl border border-orange-500/30 bg-white p-6 text-center text-black"><p className="text-xs font-black tracking-[.16em] text-orange-600">STUDENT JOIN</p><h2 className="mt-2 text-2xl font-black">QRコードを読み取る</h2><Image src={session.qrDataUrl} alt="生徒参加用QRコード" width={480} height={480} unoptimized className="mx-auto mt-4 aspect-square w-full max-w-72"/><button onClick={async()=>{await navigator.clipboard.writeText(session.joinUrl);setMessage("参加URLをコピーしました。");}} className="mt-3 inline-flex items-center gap-2 rounded-xl bg-black px-4 py-3 text-xs font-black text-white"><Copy size={15}/>URLをコピー</button><p className="mt-4 break-all text-[10px] text-black/45">{session.joinUrl}</p></section><section className="rounded-3xl border border-white/10 bg-[#101311] p-6"><div className="flex items-center"><div><p className="text-xs font-black tracking-[.16em] text-emerald-300">LIVE STATUS</p><h2 className="mt-1 text-2xl font-black">生徒の入力状況</h2></div><span className="ml-auto rounded-full bg-emerald-400/10 px-3 py-2 text-xs font-bold text-emerald-300">3秒ごとに更新</span></div><div className="mt-5 divide-y divide-white/10">{participants.length?participants.map(item=><div key={item.athlete_id} className="flex items-center py-4"><strong>{item.scan_team_athletes?.name??"選手"}</strong><span className={`ml-auto rounded-full px-3 py-1 text-xs font-bold ${item.status==="submitted"?"bg-emerald-400/15 text-emerald-300":"bg-orange-400/10 text-orange-300"}`}>{item.status==="submitted"?"提出済み":"入力中"}</span></div>):<p className="py-10 text-center text-sm text-white/35">QRコードを読み取ると、ここへ表示されます。</p>}</div><p className="mt-5 text-right text-sm font-black">提出済み {participants.filter(item=>item.status==="submitted").length}/{participants.length}名</p></section>{message?<p className="lg:col-span-2 text-sm text-emerald-300">{message}</p>:null}</div>;
 return <div className="mt-8"><section className="rounded-3xl border border-emerald-400/25 bg-[#101311] p-5 sm:p-7"><label className="text-xs font-bold text-white/45">測定日<input type="date" value={date} onChange={event=>setDate(event.target.value)} className="mt-2 block rounded-xl border border-white/15 bg-black/30 px-4 py-3 text-white [color-scheme:dark]"/></label><div className="mt-6 flex items-center justify-between"><div><p className="text-xs font-black tracking-[.16em] text-emerald-300">TODAY&apos;S TEST</p><h2 className="mt-1 text-xl font-black">本日測定する種目</h2></div><button onClick={()=>setCodes(codes.length===controlTestDefinitions.length?[]:controlTestDefinitions.map(item=>item.code))} className="text-xs font-bold text-white/50">{codes.length===controlTestDefinitions.length?"すべて解除":"すべて選択"}</button></div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{controlTestDefinitions.map(item=>{const selected=codes.includes(item.code);return <button key={item.code} onClick={()=>toggle(item.code)} className={`flex items-center gap-3 rounded-xl border p-3 text-left text-sm font-bold ${selected?"border-emerald-400/45 bg-emerald-400/10":"border-white/10 text-white/35"}`}>{selected?<CheckSquare2 size={18} className="text-emerald-300"/>:<Square size={18}/>}<span>{item.category}{item.code==="speed_endurance_300m"?"（150m・300m）":""}</span></button>})}</div><button disabled={creating||!codes.length} onClick={create} className="mt-6 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-orange-500 px-5 py-4 font-black text-black disabled:opacity-40">{creating?<LoaderCircle className="animate-spin" size={18}/>:<QrCode size={18}/>}生徒参加用QRを発行</button>{message?<p className="mt-3 text-sm text-red-300">{message}</p>:null}</section></div>}
